-- 01_seed.sql
-- Complete seed data for Dutch Language Learning API
-- Auto-generated from dutch_words.json and dutch-learning-backup.json
-- This file is automatically executed after schema creation

-- Insert CEFR levels with target counts
INSERT INTO levels (level, count) VALUES 
('A1', 500), ('A2', 1000), ('B1', 1500), ('B2', 2000), ('C1', 3000), ('C2', 5000)
ON CONFLICT (level) DO UPDATE SET count = EXCLUDED.count;

-- Insert consolidated categories (reduced from 276 to 123)
INSERT INTO categories (category) VALUES
('abandonment'),('ability'),('accommodation'),('accompaniment'),('activity'),
('age'),('application'),('approximation'),('astronomy'),('authority'),
('beginning'),('body'),('brevity'),('building'),('category'),
('change'),('classification'),('cleanliness'),('clothing'),('color'),
('commerce'),('communication'),('concession'),('conflict'),('consensus'),
('consumption'),('creation'),('culture'),('design'),('development'),
('direction'),('discovery'),('disposal'),('education'),('element'),
('emotion'),('exclusion'),('existence'),('expertise'),('feature'),
('food'),('foundation'),('function'),('future'),('global'),
('goods'),('grammar'),('health'),('housework'),('impact'),
('industry'),('information'),('intention'),('language'),('leisure'),
('life'),('location'),('luck'),('manner'),('manufacturing'),
('material'),('media'),('medical'),('mental'),('mixture'),
('money'),('movement'),('nature'),('numbers'),('object'),
('occurrence'),('ordinary'),('organization'),('origin'),('outcome'),
('people'),('person'),('personality'),('perspective'),('plan'),
('plural'),('possession'),('power'),('preference'),('presence'),
('quality'),('quantity'),('reality'),('reason'),('reflexive'),
('relation'),('relationships'),('representation'),('reputation'),('response'),
('rest'),('risk'),('royalty'),('rule'),('scenery'),
('season'),('sense'),('service'),('shape'),('singular'),
('skill'),('social'),('speed'),('stage'),('substance'),
('suggestion'),('sum'),('support'),('temperature'),('thing'),
('thought'),('time'),('topic'),('transportation'),('truth'),
('type'),('weight'),('work')
ON CONFLICT (category) DO NOTHING;

-- Insert all vocabulary words from CSV
-- Create a temporary table to load CSV data
CREATE TEMP TABLE temp_vocab_words (
    number INTEGER,
    dutch TEXT,
    english TEXT,
    part_of_speech TEXT,
    category TEXT,
    example_dutch TEXT,
    example_english TEXT
);

-- Load CSV data into temporary table
COPY temp_vocab_words(number, dutch, english, part_of_speech, category, example_dutch, example_english)
FROM '/docker-entrypoint-initdb.d/easy-vocabulary.csv'
DELIMITER ','
CSV HEADER
QUOTE '"';

-- Insert words from CSV (all at A2 level since it's "easy vocabulary")
DO $$
DECLARE
    a2_level_id INTEGER;
BEGIN
    -- Get A2 level ID
    SELECT id INTO a2_level_id FROM levels WHERE level = 'A2';

    -- Insert words from temp table (all at A2 level)
    INSERT INTO words (word, part_of_speech, level_id)
    SELECT DISTINCT dutch, part_of_speech, a2_level_id
    FROM temp_vocab_words
    ON CONFLICT (word, part_of_speech) DO NOTHING;

    -- Also insert category associations
    INSERT INTO category_words (category_id, word_id)
    SELECT DISTINCT c.id, w.id
    FROM temp_vocab_words tv
    JOIN words w ON w.word = tv.dutch AND w.part_of_speech = tv.part_of_speech
    JOIN categories c ON c.category = tv.category
    ON CONFLICT (category_id, word_id) DO NOTHING;

    -- Auto-categorize words by part of speech (for backward compatibility)
    INSERT INTO category_words (category_id, word_id)
    SELECT c.id, w.id 
    FROM categories c, words w 
    WHERE c.category = 'verbs' AND w.part_of_speech = 'verb'
    ON CONFLICT (category_id, word_id) DO NOTHING;

    INSERT INTO category_words (category_id, word_id)
    SELECT c.id, w.id 
    FROM categories c, words w 
    WHERE c.category = 'adjectives' AND w.part_of_speech = 'adjective'
    ON CONFLICT (category_id, word_id) DO NOTHING;

    INSERT INTO category_words (category_id, word_id)
    SELECT c.id, w.id 
    FROM categories c, words w 
    WHERE c.category = 'numbers' AND w.part_of_speech = 'numeral'
    ON CONFLICT (category_id, word_id) DO NOTHING;

    INSERT INTO category_words (category_id, word_id)
    SELECT c.id, w.id 
    FROM categories c, words w 
    WHERE c.category = 'prepositions' AND w.part_of_speech = 'preposition'
    ON CONFLICT (category_id, word_id) DO NOTHING;

    INSERT INTO category_words (category_id, word_id)
    SELECT c.id, w.id 
    FROM categories c, words w 
    WHERE c.category = 'articles' AND w.part_of_speech = 'article'
    ON CONFLICT (category_id, word_id) DO NOTHING;

    INSERT INTO category_words (category_id, word_id)
    SELECT c.id, w.id 
    FROM categories c, words w 
    WHERE c.category = 'pronouns' AND w.part_of_speech = 'pronoun'
    ON CONFLICT (category_id, word_id) DO NOTHING;

END $$;

-- Clean up temporary table
DROP TABLE temp_vocab_words;

-- Display summary
DO $$
DECLARE
    word_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO word_count FROM words;
    RAISE NOTICE 'Total words in database: %', word_count;
END $$;

-- Insert noun forms for Dutch nouns from easy-vocabulary.csv
-- Note: Grammatical forms (articles, diminutives, plurals) need to be filled in manually
INSERT INTO nouns
(word_id, noun, indefinite_article, diminutive, plural, possessive_form_singular, possessive_form_plural)
VALUES
((SELECT id FROM words WHERE word='aardappels' AND part_of_speech='noun' LIMIT 1), 'aardappels', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='actie' AND part_of_speech='noun' LIMIT 1), 'actie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='activiteit' AND part_of_speech='noun' LIMIT 1), 'activiteit', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='adres' AND part_of_speech='noun' LIMIT 1), 'adres', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='advies' AND part_of_speech='noun' LIMIT 1), 'advies', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='afbeelding' AND part_of_speech='noun' LIMIT 1), 'afbeelding', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='afkomst' AND part_of_speech='noun' LIMIT 1), 'afkomst', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='afwasmachine' AND part_of_speech='noun' LIMIT 1), 'afwasmachine', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='agent' AND part_of_speech='noun' LIMIT 1), 'agent', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='antwoord' AND part_of_speech='noun' LIMIT 1), 'antwoord', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='argument' AND part_of_speech='noun' LIMIT 1), 'argument', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='arm' AND part_of_speech='noun' LIMIT 1), 'arm', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='artikel' AND part_of_speech='noun' LIMIT 1), 'artikel', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='aspect' AND part_of_speech='noun' LIMIT 1), 'aspect', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='auteur' AND part_of_speech='noun' LIMIT 1), 'auteur', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='avondeten' AND part_of_speech='noun' LIMIT 1), 'avondeten', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='baan' AND part_of_speech='noun' LIMIT 1), 'baan', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='baas' AND part_of_speech='noun' LIMIT 1), 'baas', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='baby' AND part_of_speech='noun' LIMIT 1), 'baby', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='bank' AND part_of_speech='noun' LIMIT 1), 'bank', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='basis' AND part_of_speech='noun' LIMIT 1), 'basis', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='bed' AND part_of_speech='noun' LIMIT 1), 'bed', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='bedrijf' AND part_of_speech='noun' LIMIT 1), 'bedrijf', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='begin' AND part_of_speech='noun' LIMIT 1), 'begin', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='beroep' AND part_of_speech='noun' LIMIT 1), 'beroep', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='bier' AND part_of_speech='noun' LIMIT 1), 'bier', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='bijbaantje' AND part_of_speech='noun' LIMIT 1), 'bijbaantje', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='bloed' AND part_of_speech='noun' LIMIT 1), 'bloed', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='bodem' AND part_of_speech='noun' LIMIT 1), 'bodem', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='boek' AND part_of_speech='noun' LIMIT 1), 'boek', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='boodschappen' AND part_of_speech='noun' LIMIT 1), 'boodschappen', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='boot' AND part_of_speech='noun' LIMIT 1), 'boot', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='broer' AND part_of_speech='noun' LIMIT 1), 'broer', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='brood' AND part_of_speech='noun' LIMIT 1), 'brood', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='bus' AND part_of_speech='noun' LIMIT 1), 'bus', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='café' AND part_of_speech='noun' LIMIT 1), 'café', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='categorie' AND part_of_speech='noun' LIMIT 1), 'categorie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='centrum' AND part_of_speech='noun' LIMIT 1), 'centrum', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='collega' AND part_of_speech='noun' LIMIT 1), 'collega', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='combinatie' AND part_of_speech='noun' LIMIT 1), 'combinatie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='communicatie' AND part_of_speech='noun' LIMIT 1), 'communicatie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='computer' AND part_of_speech='noun' LIMIT 1), 'computer', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='conclusie' AND part_of_speech='noun' LIMIT 1), 'conclusie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='consequentie' AND part_of_speech='noun' LIMIT 1), 'consequentie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='contact' AND part_of_speech='noun' LIMIT 1), 'contact', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='crisis' AND part_of_speech='noun' LIMIT 1), 'crisis', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='cultuur' AND part_of_speech='noun' LIMIT 1), 'cultuur', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='dag' AND part_of_speech='noun' LIMIT 1), 'dag', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='detail' AND part_of_speech='noun' LIMIT 1), 'detail', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='deur' AND part_of_speech='noun' LIMIT 1), 'deur', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='ding' AND part_of_speech='noun' LIMIT 1), 'ding', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='directeur' AND part_of_speech='noun' LIMIT 1), 'directeur', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='discussie' AND part_of_speech='noun' LIMIT 1), 'discussie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='dochter' AND part_of_speech='noun' LIMIT 1), 'dochter', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='dokter' AND part_of_speech='noun' LIMIT 1), 'dokter', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='dood' AND part_of_speech='noun' LIMIT 1), 'dood', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='dorst' AND part_of_speech='noun' LIMIT 1), 'dorst', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='drinken' AND part_of_speech='noun' LIMIT 1), 'drinken', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='droom' AND part_of_speech='noun' LIMIT 1), 'droom', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='economie' AND part_of_speech='noun' LIMIT 1), 'economie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='effect' AND part_of_speech='noun' LIMIT 1), 'effect', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='ei' AND part_of_speech='noun' LIMIT 1), 'ei', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='eiland' AND part_of_speech='noun' LIMIT 1), 'eiland', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='eind' AND part_of_speech='noun' LIMIT 1), 'eind', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='emotie' AND part_of_speech='noun' LIMIT 1), 'emotie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='energie' AND part_of_speech='noun' LIMIT 1), 'energie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='eten' AND part_of_speech='noun' LIMIT 1), 'eten', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='examen' AND part_of_speech='noun' LIMIT 1), 'examen', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='experiment' AND part_of_speech='noun' LIMIT 1), 'experiment', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='fabriek' AND part_of_speech='noun' LIMIT 1), 'fabriek', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='factor' AND part_of_speech='noun' LIMIT 1), 'factor', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='familie' AND part_of_speech='noun' LIMIT 1), 'familie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='fase' AND part_of_speech='noun' LIMIT 1), 'fase', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='feit' AND part_of_speech='noun' LIMIT 1), 'feit', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='figuur' AND part_of_speech='noun' LIMIT 1), 'figuur', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='film' AND part_of_speech='noun' LIMIT 1), 'film', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='foto' AND part_of_speech='noun' LIMIT 1), 'foto', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='fruit' AND part_of_speech='noun' LIMIT 1), 'fruit', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='functie' AND part_of_speech='noun' LIMIT 1), 'functie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='gast' AND part_of_speech='noun' LIMIT 1), 'gast', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='geluk' AND part_of_speech='noun' LIMIT 1), 'geluk', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='generatie' AND part_of_speech='noun' LIMIT 1), 'generatie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='gerecht' AND part_of_speech='noun' LIMIT 1), 'gerecht', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='getallen' AND part_of_speech='noun' LIMIT 1), 'getallen', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='gevoel' AND part_of_speech='noun' LIMIT 1), 'gevoel', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='glas' AND part_of_speech='noun' LIMIT 1), 'glas', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='goederen' AND part_of_speech='noun' LIMIT 1), 'goederen', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='gras' AND part_of_speech='noun' LIMIT 1), 'gras', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='groep' AND part_of_speech='noun' LIMIT 1), 'groep', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='haar' AND part_of_speech='noun' LIMIT 1), 'haar', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='hand' AND part_of_speech='noun' LIMIT 1), 'hand', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='hart' AND part_of_speech='noun' LIMIT 1), 'hart', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='helft' AND part_of_speech='noun' LIMIT 1), 'helft', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='herfst' AND part_of_speech='noun' LIMIT 1), 'herfst', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='hoed' AND part_of_speech='noun' LIMIT 1), 'hoed', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='holland' AND part_of_speech='noun' LIMIT 1), 'holland', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='honger' AND part_of_speech='noun' LIMIT 1), 'honger', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='hoop' AND part_of_speech='noun' LIMIT 1), 'hoop', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='hotel' AND part_of_speech='noun' LIMIT 1), 'hotel', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='huis' AND part_of_speech='noun' LIMIT 1), 'huis', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='hulp' AND part_of_speech='noun' LIMIT 1), 'hulp', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='hut' AND part_of_speech='noun' LIMIT 1), 'hut', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='idee' AND part_of_speech='noun' LIMIT 1), 'idee', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='individu' AND part_of_speech='noun' LIMIT 1), 'individu', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='informatie' AND part_of_speech='noun' LIMIT 1), 'informatie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='initiatief' AND part_of_speech='noun' LIMIT 1), 'initiatief', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='instrument' AND part_of_speech='noun' LIMIT 1), 'instrument', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='invloed' AND part_of_speech='noun' LIMIT 1), 'invloed', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='jaar' AND part_of_speech='noun' LIMIT 1), 'jaar', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='jongeman' AND part_of_speech='noun' LIMIT 1), 'jongeman', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='juni' AND part_of_speech='noun' LIMIT 1), 'juni', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='kaas' AND part_of_speech='noun' LIMIT 1), 'kaas', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='kamp' AND part_of_speech='noun' LIMIT 1), 'kamp', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='karakter' AND part_of_speech='noun' LIMIT 1), 'karakter', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='kat' AND part_of_speech='noun' LIMIT 1), 'kat', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='keer' AND part_of_speech='noun' LIMIT 1), 'keer', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='kennis' AND part_of_speech='noun' LIMIT 1), 'kennis', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='kilometer' AND part_of_speech='noun' LIMIT 1), 'kilometer', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='kind' AND part_of_speech='noun' LIMIT 1), 'kind', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='klant' AND part_of_speech='noun' LIMIT 1), 'klant', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='klas' AND part_of_speech='noun' LIMIT 1), 'klas', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='kleur' AND part_of_speech='noun' LIMIT 1), 'kleur', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='knie' AND part_of_speech='noun' LIMIT 1), 'knie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='koffie' AND part_of_speech='noun' LIMIT 1), 'koffie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='koning' AND part_of_speech='noun' LIMIT 1), 'koning', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='kosten' AND part_of_speech='noun' LIMIT 1), 'kosten', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='kruis' AND part_of_speech='noun' LIMIT 1), 'kruis', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='kust' AND part_of_speech='noun' LIMIT 1), 'kust', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='kwaliteit' AND part_of_speech='noun' LIMIT 1), 'kwaliteit', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='landschap' AND part_of_speech='noun' LIMIT 1), 'landschap', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='leider' AND part_of_speech='noun' LIMIT 1), 'leider', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='leiding' AND part_of_speech='noun' LIMIT 1), 'leiding', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='lente' AND part_of_speech='noun' LIMIT 1), 'lente', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='leren' AND part_of_speech='noun' LIMIT 1), 'leren', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='leven' AND part_of_speech='noun' LIMIT 1), 'leven', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='licht' AND part_of_speech='noun' LIMIT 1), 'licht', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='liefde' AND part_of_speech='noun' LIMIT 1), 'liefde', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='lijst' AND part_of_speech='noun' LIMIT 1), 'lijst', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='lip' AND part_of_speech='noun' LIMIT 1), 'lip', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='literatuur' AND part_of_speech='noun' LIMIT 1), 'literatuur', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='luitenant' AND part_of_speech='noun' LIMIT 1), 'luitenant', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='maaltijd' AND part_of_speech='noun' LIMIT 1), 'maaltijd', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='maan' AND part_of_speech='noun' LIMIT 1), 'maan', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='maand' AND part_of_speech='noun' LIMIT 1), 'maand', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='machine' AND part_of_speech='noun' LIMIT 1), 'machine', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='mama' AND part_of_speech='noun' LIMIT 1), 'mama', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='man' AND part_of_speech='noun' LIMIT 1), 'man', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='markt' AND part_of_speech='noun' LIMIT 1), 'markt', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='materiaal' AND part_of_speech='noun' LIMIT 1), 'materiaal', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='meer' AND part_of_speech='noun' LIMIT 1), 'meer', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='meester' AND part_of_speech='noun' LIMIT 1), 'meester', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='meter' AND part_of_speech='noun' LIMIT 1), 'meter', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='methode' AND part_of_speech='noun' LIMIT 1), 'methode', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='minister' AND part_of_speech='noun' LIMIT 1), 'minister', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='minuut' AND part_of_speech='noun' LIMIT 1), 'minuut', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='moeder' AND part_of_speech='noun' LIMIT 1), 'moeder', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='moment' AND part_of_speech='noun' LIMIT 1), 'moment', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='mond' AND part_of_speech='noun' LIMIT 1), 'mond', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='motief' AND part_of_speech='noun' LIMIT 1), 'motief', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='museum' AND part_of_speech='noun' LIMIT 1), 'museum', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='muziek' AND part_of_speech='noun' LIMIT 1), 'muziek', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='naam' AND part_of_speech='noun' LIMIT 1), 'naam', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='nacht' AND part_of_speech='noun' LIMIT 1), 'nacht', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='natuur' AND part_of_speech='noun' LIMIT 1), 'natuur', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='neef' AND part_of_speech='noun' LIMIT 1), 'neef', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='nek' AND part_of_speech='noun' LIMIT 1), 'nek', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='neus' AND part_of_speech='noun' LIMIT 1), 'neus', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='nicht' AND part_of_speech='noun' LIMIT 1), 'nicht', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='noorden' AND part_of_speech='noun' LIMIT 1), 'noorden', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='nummer' AND part_of_speech='noun' LIMIT 1), 'nummer', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='object' AND part_of_speech='noun' LIMIT 1), 'object', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='officier' AND part_of_speech='noun' LIMIT 1), 'officier', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='oktober' AND part_of_speech='noun' LIMIT 1), 'oktober', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='olie' AND part_of_speech='noun' LIMIT 1), 'olie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='oma' AND part_of_speech='noun' LIMIT 1), 'oma', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='oom' AND part_of_speech='noun' LIMIT 1), 'oom', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='oor' AND part_of_speech='noun' LIMIT 1), 'oor', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='opa' AND part_of_speech='noun' LIMIT 1), 'opa', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='operatie' AND part_of_speech='noun' LIMIT 1), 'operatie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='orgaan' AND part_of_speech='noun' LIMIT 1), 'orgaan', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='organisatie' AND part_of_speech='noun' LIMIT 1), 'organisatie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='ouders' AND part_of_speech='noun' LIMIT 1), 'ouders', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='pad' AND part_of_speech='noun' LIMIT 1), 'pad', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='papier' AND part_of_speech='noun' LIMIT 1), 'papier', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='partner' AND part_of_speech='noun' LIMIT 1), 'partner', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='pas' AND part_of_speech='noun' LIMIT 1), 'pas', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='patiënt' AND part_of_speech='noun' LIMIT 1), 'patiënt', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='patroon' AND part_of_speech='noun' LIMIT 1), 'patroon', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='periode' AND part_of_speech='noun' LIMIT 1), 'periode', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='pers' AND part_of_speech='noun' LIMIT 1), 'pers', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='persoon' AND part_of_speech='noun' LIMIT 1), 'persoon', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='persoonlijkheid' AND part_of_speech='noun' LIMIT 1), 'persoonlijkheid', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='pijn' AND part_of_speech='noun' LIMIT 1), 'pijn', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='plaat' AND part_of_speech='noun' LIMIT 1), 'plaat', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='plaats' AND part_of_speech='noun' LIMIT 1), 'plaats', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='plan' AND part_of_speech='noun' LIMIT 1), 'plan', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='plant' AND part_of_speech='noun' LIMIT 1), 'plant', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='plezier' AND part_of_speech='noun' LIMIT 1), 'plezier', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='politie' AND part_of_speech='noun' LIMIT 1), 'politie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='positie' AND part_of_speech='noun' LIMIT 1), 'positie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='pot' AND part_of_speech='noun' LIMIT 1), 'pot', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='praktijk' AND part_of_speech='noun' LIMIT 1), 'praktijk', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='president' AND part_of_speech='noun' LIMIT 1), 'president', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='prijs' AND part_of_speech='noun' LIMIT 1), 'prijs', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='probleem' AND part_of_speech='noun' LIMIT 1), 'probleem', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='procent' AND part_of_speech='noun' LIMIT 1), 'procent', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='proces' AND part_of_speech='noun' LIMIT 1), 'proces', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='product' AND part_of_speech='noun' LIMIT 1), 'product', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='productie' AND part_of_speech='noun' LIMIT 1), 'productie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='programma' AND part_of_speech='noun' LIMIT 1), 'programma', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='project' AND part_of_speech='noun' LIMIT 1), 'project', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='provincie' AND part_of_speech='noun' LIMIT 1), 'provincie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='psychologie' AND part_of_speech='noun' LIMIT 1), 'psychologie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='psycholoog' AND part_of_speech='noun' LIMIT 1), 'psycholoog', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='radio' AND part_of_speech='noun' LIMIT 1), 'radio', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='reactie' AND part_of_speech='noun' LIMIT 1), 'reactie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='reden' AND part_of_speech='noun' LIMIT 1), 'reden', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='regel' AND part_of_speech='noun' LIMIT 1), 'regel', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='relatie' AND part_of_speech='noun' LIMIT 1), 'relatie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='restaurant' AND part_of_speech='noun' LIMIT 1), 'restaurant', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='resultaat' AND part_of_speech='noun' LIMIT 1), 'resultaat', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='rijk' AND part_of_speech='noun' LIMIT 1), 'rijk', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='risico' AND part_of_speech='noun' LIMIT 1), 'risico', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='rivier' AND part_of_speech='noun' LIMIT 1), 'rivier', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='roepnaam' AND part_of_speech='noun' LIMIT 1), 'roepnaam', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='rol' AND part_of_speech='noun' LIMIT 1), 'rol', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='rommel' AND part_of_speech='noun' LIMIT 1), 'rommel', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='rust' AND part_of_speech='noun' LIMIT 1), 'rust', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='schaduw' AND part_of_speech='noun' LIMIT 1), 'schaduw', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='schoen' AND part_of_speech='noun' LIMIT 1), 'schoen', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='school' AND part_of_speech='noun' LIMIT 1), 'school', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='schouder' AND part_of_speech='noun' LIMIT 1), 'schouder', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='seconde' AND part_of_speech='noun' LIMIT 1), 'seconde', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='sector' AND part_of_speech='noun' LIMIT 1), 'sector', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='sigaret' AND part_of_speech='noun' LIMIT 1), 'sigaret', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='slaap' AND part_of_speech='noun' LIMIT 1), 'slaap', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='sneeuw' AND part_of_speech='noun' LIMIT 1), 'sneeuw', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='soort' AND part_of_speech='noun' LIMIT 1), 'soort', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='staan' AND part_of_speech='noun' LIMIT 1), 'staan', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='staat' AND part_of_speech='noun' LIMIT 1), 'staat', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='stap' AND part_of_speech='noun' LIMIT 1), 'stap', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='station' AND part_of_speech='noun' LIMIT 1), 'station', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='steen' AND part_of_speech='noun' LIMIT 1), 'steen', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='ster' AND part_of_speech='noun' LIMIT 1), 'ster', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='stijl' AND part_of_speech='noun' LIMIT 1), 'stijl', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='straat' AND part_of_speech='noun' LIMIT 1), 'straat', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='structuur' AND part_of_speech='noun' LIMIT 1), 'structuur', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='student' AND part_of_speech='noun' LIMIT 1), 'student', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='studie' AND part_of_speech='noun' LIMIT 1), 'studie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='succes' AND part_of_speech='noun' LIMIT 1), 'succes', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='suiker' AND part_of_speech='noun' LIMIT 1), 'suiker', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='symbool' AND part_of_speech='noun' LIMIT 1), 'symbool', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='systeem' AND part_of_speech='noun' LIMIT 1), 'systeem', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='tafel' AND part_of_speech='noun' LIMIT 1), 'tafel', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='tante' AND part_of_speech='noun' LIMIT 1), 'tante', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='techniek' AND part_of_speech='noun' LIMIT 1), 'techniek', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='tekst' AND part_of_speech='noun' LIMIT 1), 'tekst', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='telefoon' AND part_of_speech='noun' LIMIT 1), 'telefoon', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='televisie' AND part_of_speech='noun' LIMIT 1), 'televisie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='tentamen' AND part_of_speech='noun' LIMIT 1), 'tentamen', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='term' AND part_of_speech='noun' LIMIT 1), 'term', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='terras' AND part_of_speech='noun' LIMIT 1), 'terras', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='terrein' AND part_of_speech='noun' LIMIT 1), 'terrein', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='thee' AND part_of_speech='noun' LIMIT 1), 'thee', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='theorie' AND part_of_speech='noun' LIMIT 1), 'theorie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='titel' AND part_of_speech='noun' LIMIT 1), 'titel', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='toetje' AND part_of_speech='noun' LIMIT 1), 'toetje', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='toets' AND part_of_speech='noun' LIMIT 1), 'toets', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='tong' AND part_of_speech='noun' LIMIT 1), 'tong', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='top' AND part_of_speech='noun' LIMIT 1), 'top', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='traditie' AND part_of_speech='noun' LIMIT 1), 'traditie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='trein' AND part_of_speech='noun' LIMIT 1), 'trein', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='tuin' AND part_of_speech='noun' LIMIT 1), 'tuin', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='universiteit' AND part_of_speech='noun' LIMIT 1), 'universiteit', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='uur' AND part_of_speech='noun' LIMIT 1), 'uur', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='vader' AND part_of_speech='noun' LIMIT 1), 'vader', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='veld' AND part_of_speech='noun' LIMIT 1), 'veld', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='verjaardag' AND part_of_speech='noun' LIMIT 1), 'verjaardag', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='vinger' AND part_of_speech='noun' LIMIT 1), 'vinger', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='vis' AND part_of_speech='noun' LIMIT 1), 'vis', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='visie' AND part_of_speech='noun' LIMIT 1), 'visie', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='vloer' AND part_of_speech='noun' LIMIT 1), 'vloer', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='voet' AND part_of_speech='noun' LIMIT 1), 'voet', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='vorming' AND part_of_speech='noun' LIMIT 1), 'vorming', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='vriend' AND part_of_speech='noun' LIMIT 1), 'vriend', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='vrienden' AND part_of_speech='noun' LIMIT 1), 'vrienden', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='vriendin' AND part_of_speech='noun' LIMIT 1), 'vriendin', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='vriendinnen' AND part_of_speech='noun' LIMIT 1), 'vriendinnen', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='vuilnis' AND part_of_speech='noun' LIMIT 1), 'vuilnis', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='vuur' AND part_of_speech='noun' LIMIT 1), 'vuur', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='wapen' AND part_of_speech='noun' LIMIT 1), 'wapen', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='warmte' AND part_of_speech='noun' LIMIT 1), 'warmte', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='wasmachine' AND part_of_speech='noun' LIMIT 1), 'wasmachine', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='water' AND part_of_speech='noun' LIMIT 1), 'water', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='week' AND part_of_speech='noun' LIMIT 1), 'week', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='weer' AND part_of_speech='noun' LIMIT 1), 'weer', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='wens' AND part_of_speech='noun' LIMIT 1), 'wens', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='wereld' AND part_of_speech='noun' LIMIT 1), 'wereld', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='werk' AND part_of_speech='noun' LIMIT 1), 'werk', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='westen' AND part_of_speech='noun' LIMIT 1), 'westen', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='wetenschap' AND part_of_speech='noun' LIMIT 1), 'wetenschap', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='wijn' AND part_of_speech='noun' LIMIT 1), 'wijn', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='wind' AND part_of_speech='noun' LIMIT 1), 'wind', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='winter' AND part_of_speech='noun' LIMIT 1), 'winter', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='woord' AND part_of_speech='noun' LIMIT 1), 'woord', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='zaken' AND part_of_speech='noun' LIMIT 1), 'zaken', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='zand' AND part_of_speech='noun' LIMIT 1), 'zand', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='zee' AND part_of_speech='noun' LIMIT 1), 'zee', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='zomer' AND part_of_speech='noun' LIMIT 1), 'zomer', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='zondag' AND part_of_speech='noun' LIMIT 1), 'zondag', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='zoon' AND part_of_speech='noun' LIMIT 1), 'zoon', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='zout' AND part_of_speech='noun' LIMIT 1), 'zout', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='zus' AND part_of_speech='noun' LIMIT 1), 'zus', NULL, NULL, NULL, NULL, NULL),
((SELECT id FROM words WHERE word='zuster' AND part_of_speech='noun' LIMIT 1), 'zuster', NULL, NULL, NULL, NULL, NULL)
ON CONFLICT (word_id) DO NOTHING;

-- Create numeral forms for Dutch numerals (explicit rows mirroring nouns style)
INSERT INTO numerals (word_id, numeral, numeric_value, ordinal_form) VALUES
((SELECT id FROM words WHERE word = 'een' AND part_of_speech = 'numeral' LIMIT 1), 'een', 1, 'eerste'),
((SELECT id FROM words WHERE word = 'twee' AND part_of_speech = 'numeral' LIMIT 1), 'twee', 2, 'tweede'),
((SELECT id FROM words WHERE word = 'drie' AND part_of_speech = 'numeral' LIMIT 1), 'drie', 3, 'derde'),
((SELECT id FROM words WHERE word = 'vier' AND part_of_speech = 'numeral' LIMIT 1), 'vier', 4, 'vierde'),
((SELECT id FROM words WHERE word = 'vijf' AND part_of_speech = 'numeral' LIMIT 1), 'vijf', 5, 'vijfde'),
((SELECT id FROM words WHERE word = 'zes' AND part_of_speech = 'numeral' LIMIT 1), 'zes', 6, 'zesde'),
((SELECT id FROM words WHERE word = 'zeven' AND part_of_speech = 'numeral' LIMIT 1), 'zeven', 7, 'zevende'),
((SELECT id FROM words WHERE word = 'acht' AND part_of_speech = 'numeral' LIMIT 1), 'acht', 8, 'achtste'),
((SELECT id FROM words WHERE word = 'negen' AND part_of_speech = 'numeral' LIMIT 1), 'negen', 9, 'negende'),
((SELECT id FROM words WHERE word = 'tien' AND part_of_speech = 'numeral' LIMIT 1), 'tien', 10, 'tiende'),
((SELECT id FROM words WHERE word = 'elf' AND part_of_speech = 'numeral' LIMIT 1), 'elf', 11, 'elfde'),
((SELECT id FROM words WHERE word = 'twaalf' AND part_of_speech = 'numeral' LIMIT 1), 'twaalf', 12, 'twaalfde'),
((SELECT id FROM words WHERE word = 'dertien' AND part_of_speech = 'numeral' LIMIT 1), 'dertien', 13, 'dertiende'),
((SELECT id FROM words WHERE word = 'veertien' AND part_of_speech = 'numeral' LIMIT 1), 'veertien', 14, 'veertiende'),
((SELECT id FROM words WHERE word = 'vijftien' AND part_of_speech = 'numeral' LIMIT 1), 'vijftien', 15, 'vijftiende'),
((SELECT id FROM words WHERE word = 'zestien' AND part_of_speech = 'numeral' LIMIT 1), 'zestien', 16, 'zestiende'),
((SELECT id FROM words WHERE word = 'zeventien' AND part_of_speech = 'numeral' LIMIT 1), 'zeventien', 17, 'zeventiende'),
((SELECT id FROM words WHERE word = 'achttien' AND part_of_speech = 'numeral' LIMIT 1), 'achttien', 18, 'achttiende'),
((SELECT id FROM words WHERE word = 'negentien' AND part_of_speech = 'numeral' LIMIT 1), 'negentien', 19, 'negentiende'),
((SELECT id FROM words WHERE word = 'twintig' AND part_of_speech = 'numeral' LIMIT 1), 'twintig', 20, 'twintigste'),
((SELECT id FROM words WHERE word = 'dertig' AND part_of_speech = 'numeral' LIMIT 1), 'dertig', 30, 'dertigste'),
((SELECT id FROM words WHERE word = 'veertig' AND part_of_speech = 'numeral' LIMIT 1), 'veertig', 40, 'veertigste'),
((SELECT id FROM words WHERE word = 'vijftig' AND part_of_speech = 'numeral' LIMIT 1), 'vijftig', 50, 'vijftigste'),
((SELECT id FROM words WHERE word = 'honderd' AND part_of_speech = 'numeral' LIMIT 1), 'honderd', 100, 'honderdste'),
((SELECT id FROM words WHERE word = 'duizend' AND part_of_speech = 'numeral' LIMIT 1), 'duizend', 1000, 'duizendste'),
((SELECT id FROM words WHERE word = 'achthonderdzesentwintig' AND part_of_speech = 'numeral' LIMIT 1), 'achthonderdzesentwintig', 84, 'achthonderdzesentwintigste'),
((SELECT id FROM words WHERE word = 'vierentachtig' AND part_of_speech = 'numeral' LIMIT 1), 'vierentachtig', 84, 'vierentachtigste'),
((SELECT id FROM words WHERE word = 'vierentwintig' AND part_of_speech = 'numeral' LIMIT 1), 'vierentwintig', 24, 'vierentwintigste'),
((SELECT id FROM words WHERE word = 'zeshonderd' AND part_of_speech = 'numeral' LIMIT 1), 'zeshonderd', 600, 'zeshonderdste'),
((SELECT id FROM words WHERE word = 'zevenhonderdnegenennegentig' AND part_of_speech = 'numeral' LIMIT 1), 'zevenhonderdnegenennegentig', 799, 'zevenhonderdnegenennegentigste')
ON CONFLICT (word_id) DO NOTHING;
-- Create adjective forms for Dutch adjectives (explicit rows)
INSERT INTO adjectives (word_id, adjective, de_form, comparison, superlative) VALUES
((SELECT id FROM words WHERE word = 'groot' AND part_of_speech = 'adjective' LIMIT 1), 'groot', 'grote', 'groter', 'grootste'),
((SELECT id FROM words WHERE word = 'klein' AND part_of_speech = 'adjective' LIMIT 1), 'klein', 'kleine', 'kleiner', 'kleinste'),
((SELECT id FROM words WHERE word = 'oud' AND part_of_speech = 'adjective' LIMIT 1), 'oud', 'oude', 'ouder', 'oudste'),
((SELECT id FROM words WHERE word = 'nieuw' AND part_of_speech = 'adjective' LIMIT 1), 'nieuw', 'nieuwe', 'nieuwer', 'nieuwste'),
((SELECT id FROM words WHERE word = 'mooi' AND part_of_speech = 'adjective' LIMIT 1), 'mooi', 'mooie', 'mooier', 'mooiste'),
((SELECT id FROM words WHERE word = 'lelijk' AND part_of_speech = 'adjective' LIMIT 1), 'lelijk', 'lelijke', 'lelijker', 'lelijkste'),
((SELECT id FROM words WHERE word = 'goed' AND part_of_speech = 'adjective' LIMIT 1), 'goed', 'goede', 'beter', 'best'),
((SELECT id FROM words WHERE word = 'slecht' AND part_of_speech = 'adjective' LIMIT 1), 'slecht', 'slechte', 'slechter', 'slechtst'),
((SELECT id FROM words WHERE word = 'snel' AND part_of_speech = 'adjective' LIMIT 1), 'snel', 'snelle', 'sneller', 'snelst'),
((SELECT id FROM words WHERE word = 'langzaam' AND part_of_speech = 'adjective' LIMIT 1), 'langzaam', 'langzame', 'langzamer', 'langzaamste'),
((SELECT id FROM words WHERE word = 'warm' AND part_of_speech = 'adjective' LIMIT 1), 'warm', 'warme', 'warmer', 'warmste'),
((SELECT id FROM words WHERE word = 'koud' AND part_of_speech = 'adjective' LIMIT 1), 'koud', 'koude', 'kouder', 'koudste'),
((SELECT id FROM words WHERE word = 'moeilijk' AND part_of_speech = 'adjective' LIMIT 1), 'moeilijk', 'moeilijke', 'moeilijker', 'moeilijkste'),
((SELECT id FROM words WHERE word = 'makkelijk' AND part_of_speech = 'adjective' LIMIT 1), 'makkelijk', 'makkelijke', 'makkelijker', 'makkelijkste'),
((SELECT id FROM words WHERE word = 'lang' AND part_of_speech = 'adjective' LIMIT 1), 'lang', 'lange', 'langer', 'langste'),
((SELECT id FROM words WHERE word = 'kort' AND part_of_speech = 'adjective' LIMIT 1), 'kort', 'korte', 'korter', 'kortste'),
((SELECT id FROM words WHERE word = 'interessant' AND part_of_speech = 'adjective' LIMIT 1), 'interessant', 'interessante', 'interessanter', 'interessantste'),
((SELECT id FROM words WHERE word = 'belangrijk' AND part_of_speech = 'adjective' LIMIT 1), 'belangrijk', 'belangrijke', 'belangrijker', 'belangrijkste'),
((SELECT id FROM words WHERE word='al' AND part_of_speech='adjective' LIMIT 1), 'al','alle',NULL,NULL),
((SELECT id FROM words WHERE word='allemaal' AND part_of_speech='adjective' LIMIT 1), 'allemaal','allemaal',NULL,NULL),
((SELECT id FROM words WHERE word='allebei' AND part_of_speech='adjective' LIMIT 1), 'allebei','allebei',NULL,NULL),
((SELECT id FROM words WHERE word='ander' AND part_of_speech='adjective' LIMIT 1), 'ander','andere',NULL,NULL),
((SELECT id FROM words WHERE word='elk' AND part_of_speech='adjective' LIMIT 1), 'elk','elke',NULL,NULL),
((SELECT id FROM words WHERE word='ieder' AND part_of_speech='adjective' LIMIT 1), 'ieder','iedere',NULL,NULL),
((SELECT id FROM words WHERE word='sommige' AND part_of_speech='adjective' LIMIT 1), 'sommige','sommige',NULL,NULL),
((SELECT id FROM words WHERE word='geen' AND part_of_speech='adjective' LIMIT 1), 'geen','geen',NULL,NULL),
((SELECT id FROM words WHERE word='je' AND part_of_speech='adjective' LIMIT 1), 'je','je',NULL,NULL),
((SELECT id FROM words WHERE word='jouw' AND part_of_speech='adjective' LIMIT 1), 'jouw','jouw',NULL,NULL),
((SELECT id FROM words WHERE word='mijn' AND part_of_speech='adjective' LIMIT 1), 'mijn','mijn',NULL,NULL),
((SELECT id FROM words WHERE word='uw' AND part_of_speech='adjective' LIMIT 1), 'uw','uw',NULL,NULL),
((SELECT id FROM words WHERE word='arm' AND part_of_speech='adjective' LIMIT 1), 'arm','arme','armer','armste'),
((SELECT id FROM words WHERE word='bruin' AND part_of_speech='adjective' LIMIT 1), 'bruin','bruine','bruiner','bruinste'),
((SELECT id FROM words WHERE word='druk' AND part_of_speech='adjective' LIMIT 1), 'druk','drukke','drukker','drukste'),
((SELECT id FROM words WHERE word='gelukkig' AND part_of_speech='adjective' LIMIT 1), 'gelukkig','gelukkige','gelukkiger','gelukkigste'),
((SELECT id FROM words WHERE word='leuk' AND part_of_speech='adjective' LIMIT 1), 'leuk','leuke','leuker','leukste'),
((SELECT id FROM words WHERE word='los' AND part_of_speech='adjective' LIMIT 1), 'los','losse','losser','losste'),
((SELECT id FROM words WHERE word='net' AND part_of_speech='adjective' LIMIT 1), 'net','nette','netter','netste'),
((SELECT id FROM words WHERE word='vast' AND part_of_speech='adjective' LIMIT 1), 'vast','vaste','vaster','vastste'),
((SELECT id FROM words WHERE word='diep' AND part_of_speech='adjective' LIMIT 1), 'diep','diepe','dieper','diepste'),
((SELECT id FROM words WHERE word='typisch' AND part_of_speech='adjective' LIMIT 1), 'typisch','typische','typischer','typischste'),
((SELECT id FROM words WHERE word='verticaal' AND part_of_speech='adjective' LIMIT 1), 'verticaal','verticale','verticaler','verticalste'),
((SELECT id FROM words WHERE word='geel' AND part_of_speech='adjective' LIMIT 1), 'geel','gele','geler','geelste'),
((SELECT id FROM words WHERE word='goed' AND part_of_speech='adjective' LIMIT 1), 'goed','goede','beter','beste'),
((SELECT id FROM words WHERE word='lang' AND part_of_speech='adjective' LIMIT 1), 'lang','lange','langer','langste'),
((SELECT id FROM words WHERE word='geboren' AND part_of_speech='adjective' LIMIT 1), 'geboren','geboren',NULL,NULL),
((SELECT id FROM words WHERE word='gesloten' AND part_of_speech='adjective' LIMIT 1), 'gesloten','gesloten',NULL,NULL),
((SELECT id FROM words WHERE word='mogelijk' AND part_of_speech='adjective' LIMIT 1), 'mogelijk','mogelijke',NULL,NULL),
((SELECT id FROM words WHERE word='openbaar' AND part_of_speech='adjective' LIMIT 1), 'openbaar','openbare',NULL,NULL),
((SELECT id FROM words WHERE word='voorbehouden' AND part_of_speech='adjective' LIMIT 1), 'voorbehouden','voorbehouden',NULL,NULL),
((SELECT id FROM words WHERE word='juist' AND part_of_speech='adjective' LIMIT 1), 'juist','juiste',NULL,NULL),
((SELECT id FROM words WHERE word='waar' AND part_of_speech='adjective' LIMIT 1), 'waar','ware',NULL,NULL),
((SELECT id FROM words WHERE word='open' AND part_of_speech='adjective' LIMIT 1), 'open','open','opener','openste'),
((SELECT id FROM words WHERE word='deens' AND part_of_speech='adjective' LIMIT 1), 'deens','deense',NULL,NULL),
((SELECT id FROM words WHERE word='duits' AND part_of_speech='adjective' LIMIT 1), 'duits','duitse',NULL,NULL),
((SELECT id FROM words WHERE word='engels' AND part_of_speech='adjective' LIMIT 1), 'engels','engelse',NULL,NULL),
((SELECT id FROM words WHERE word='europees' AND part_of_speech='adjective' LIMIT 1), 'europees','europese',NULL,NULL),
((SELECT id FROM words WHERE word='frans' AND part_of_speech='adjective' LIMIT 1), 'frans','franse',NULL,NULL),
((SELECT id FROM words WHERE word='italiaans' AND part_of_speech='adjective' LIMIT 1), 'italiaans','italiaanse',NULL,NULL),
((SELECT id FROM words WHERE word='nederlands' AND part_of_speech='adjective' LIMIT 1), 'nederlands','nederlandse',NULL,NULL),
((SELECT id FROM words WHERE word='russisch' AND part_of_speech='adjective' LIMIT 1), 'russisch','russische',NULL,NULL),
((SELECT id FROM words WHERE word='akoestisch' AND part_of_speech='adjective' LIMIT 1), 'akoestisch','akoestische','akoestischer','akoestischste'),
((SELECT id FROM words WHERE word='anderstalig' AND part_of_speech='adjective' LIMIT 1), 'anderstalig','anderstalige','anderstaliger','anderstaligste'),
((SELECT id FROM words WHERE word='benodigd' AND part_of_speech='adjective' LIMIT 1), 'benodigd','benodigde',NULL,NULL),
((SELECT id FROM words WHERE word='bijbehorend' AND part_of_speech='adjective' LIMIT 1), 'bijbehorend','bijbehorende','bijbehorender','bijbehorendste'),
((SELECT id FROM words WHERE word='communicatief' AND part_of_speech='adjective' LIMIT 1), 'communicatief','communicatieve','communicatiever','communicatiefste'),
((SELECT id FROM words WHERE word='driedelig' AND part_of_speech='adjective' LIMIT 1), 'driedelig','driedelige','driedeliger','driedeligste'),
((SELECT id FROM words WHERE word='filmisch' AND part_of_speech='adjective' LIMIT 1), 'filmisch','filmische','filmischer','filmischste'),
((SELECT id FROM words WHERE word='functioneel' AND part_of_speech='adjective' LIMIT 1), 'functioneel','functionele','functioneler','functioneelste'),
((SELECT id FROM words WHERE word='grafisch' AND part_of_speech='adjective' LIMIT 1), 'grafisch','grafische','grafischer','grafischste'),
((SELECT id FROM words WHERE word='grammaticaal' AND part_of_speech='adjective' LIMIT 1), 'grammaticaal','grammaticale','grammaticaler','grammaticaalste'),
((SELECT id FROM words WHERE word='hoogopgeleid' AND part_of_speech='adjective' LIMIT 1), 'hoogopgeleid','hoogopgeleide','hoogopgeleider','hoogopgeleidste'),
((SELECT id FROM words WHERE word='ingescand' AND part_of_speech='adjective' LIMIT 1), 'ingescand','ingescand',NULL,NULL),
((SELECT id FROM words WHERE word='interrogatief' AND part_of_speech='adjective' LIMIT 1), 'interrogatief','interrogatieve','interrogatiever','interrogatiefste'),
((SELECT id FROM words WHERE word='lexicaal' AND part_of_speech='adjective' LIMIT 1), 'lexicaal','lexicale','lexicaler','lexicaalste'),
((SELECT id FROM words WHERE word='modern' AND part_of_speech='adjective' LIMIT 1), 'modern','moderne','moderner','modernste'),
((SELECT id FROM words WHERE word='nederlandstalig' AND part_of_speech='adjective' LIMIT 1), 'nederlandstalig','nederlandstalige','nederlandstaliger','nederlandstaligste'),
((SELECT id FROM words WHERE word='productief' AND part_of_speech='adjective' LIMIT 1), 'productief','productieve','productiever','productiefste'),
((SELECT id FROM words WHERE word='realistisch' AND part_of_speech='adjective' LIMIT 1), 'realistisch','realistische','realistischer','realistischste'),
((SELECT id FROM words WHERE word='receptief' AND part_of_speech='adjective' LIMIT 1), 'receptief','receptieve','receptiever','receptiefste'),
((SELECT id FROM words WHERE word='schriftelijk' AND part_of_speech='adjective' LIMIT 1), 'schriftelijk','schriftelijke','schriftelijker','schriftelijkste'),
((SELECT id FROM words WHERE word='relatief' AND part_of_speech='adjective' LIMIT 1), 'relatief','relatieve','relatiever','relatiefste'),
((SELECT id FROM words WHERE word='volgend' AND part_of_speech='adjective' LIMIT 1), 'volgend','volgende',NULL,NULL),
((SELECT id FROM words WHERE word='voorafgaand' AND part_of_speech='adjective' LIMIT 1), 'voorafgaand','voorafgaande',NULL,NULL),
((SELECT id FROM words WHERE word='verenigd' AND part_of_speech='adjective' LIMIT 1), 'verenigd','verenigde',NULL,NULL),
((SELECT id FROM words WHERE word='even' AND part_of_speech='adjective' LIMIT 1), 'even','even',NULL,NULL),
((SELECT id FROM words WHERE word='best' AND part_of_speech='adjective' LIMIT 1), 'best','beste',NULL,NULL)
ON CONFLICT (word_id) DO NOTHING;

-- Create verb forms for common Dutch verbs (explicit rows)
INSERT INTO verbs (
    infinitive,
    present_simple_1st_singular,
    present_simple_2nd_singular,
    present_simple_2nd_respectful,
    present_simple_3rd_singular,
    present_simple_plural,
    past_simple_singular,
    past_simple_plural,
    past_participle,
    perfect_auxiliary,
    separable_prefix,
    is_separable,
    is_irregular,
    is_strong_verb,
    is_modal,
    word_id
)
VALUES
('gelden', 'geld','geldt','geldt','geldt','gelden','gold','golden','gegolden','hebben', NULL,false,true,false,false,(SELECT id FROM words WHERE word='gelden' AND part_of_speech='verb' LIMIT 1)),
('houden', 'houd','houdt','houdt','houdt','houden','hield','hielden','gehouden','hebben', NULL,false,true,false,false,(SELECT id FROM words WHERE word='houden' AND part_of_speech='verb' LIMIT 1)),
('zijn',    'ben','bent','bent','is','zijn','was','waren','geweest','zijn',   NULL,false,true, true, false,(SELECT id FROM words WHERE word='zijn'    AND part_of_speech='verb' LIMIT 1)),
('hebben',  'heb','hebt','hebt','heeft','hebben','had','hadden','gehad','hebben',NULL,false,true, false,false,(SELECT id FROM words WHERE word='hebben'  AND part_of_speech='verb' LIMIT 1)),
('gaan',    'ga', 'gaat','gaat','gaat','gaan','ging','gingen','gegaan','zijn', NULL,false,true, true, false,(SELECT id FROM words WHERE word='gaan'    AND part_of_speech='verb' LIMIT 1)),
('komen',   'kom','komt','komt','komt','komen','kwam','kwamen','gekomen','zijn',NULL,false,true, true, false,(SELECT id FROM words WHERE word='komen'   AND part_of_speech='verb' LIMIT 1)),
('doen',    'doe','doet','doet','doet','doen','deed','deden','gedaan','hebben', NULL,false,true, true, false,(SELECT id FROM words WHERE word='doen'    AND part_of_speech='verb' LIMIT 1)),
('zien',    'zie','ziet','ziet','ziet','zien','zag','zagen','gezien','hebben',  NULL,false,true, true, false,(SELECT id FROM words WHERE word='zien'    AND part_of_speech='verb' LIMIT 1)),
('kunnen',  'kan','kunt','kunt','kan','kunnen','kon','konden','gekund','hebben', NULL,false,true, false,true, (SELECT id FROM words WHERE word='kunnen'  AND part_of_speech='verb' LIMIT 1)),
('willen',  'wil','wilt','wilt','wil','willen','wilde','wilden','gewild','hebben',NULL,false,true, false,true, (SELECT id FROM words WHERE word='willen'  AND part_of_speech='verb' LIMIT 1)),
('moeten',  'moet','moet','moet','moet','moeten','moest','moesten','gemoeten','hebben',NULL,false,true, false,true, (SELECT id FROM words WHERE word='moeten'  AND part_of_speech='verb' LIMIT 1)),
('mogen',   'mag','mag','mag','mag','mogen','mocht','mochten','gemogen','hebben',NULL,false,true, false,true, (SELECT id FROM words WHERE word='mogen'   AND part_of_speech='verb' LIMIT 1)),
('zeggen',  'zeg','zegt','zegt','zegt','zeggen','zei','zeiden','gezegd','hebben',NULL,false,true, false,false,(SELECT id FROM words WHERE word='zeggen'  AND part_of_speech='verb' LIMIT 1)),
('maken',   'maak','maakt','maakt','maakt','maken','maakte','maakten','gemaakt','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='maken'   AND part_of_speech='verb' LIMIT 1)),
('nemen',   'neem','neemt','neemt','neemt','nemen','nam','namen','genomen','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='nemen'   AND part_of_speech='verb' LIMIT 1)),
('geven',   'geef','geeft','geeft','geeft','geven','gaf','gaven','gegeven','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='geven'   AND part_of_speech='verb' LIMIT 1)),
('werken',  'werk','werkt','werkt','werkt','werken','werkte','werkten','gewerkt','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='werken'  AND part_of_speech='verb' LIMIT 1)),
('lezen',   'lees','leest','leest','leest','lezen','las','lazen','gelezen','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='lezen'   AND part_of_speech='verb' LIMIT 1)),
('schrijven','schrijf','schrijft','schrijft','schrijft','schrijven','schreef','schreven','geschreven','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='schrijven'AND part_of_speech='verb' LIMIT 1)),
('eten',    'eet','eet','eet','eet','eten','at','aten','gegeten','hebben', NULL,false,true, true, false,(SELECT id FROM words WHERE word='eten'    AND part_of_speech='verb' LIMIT 1)),
('drinken', 'drink','drinkt','drinkt','drinkt','drinken','dronk','dronken','gedronken','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='drinken' AND part_of_speech='verb' LIMIT 1)),
('slapen',  'slaap','slaapt','slaapt','slaapt','slapen','sliep','sliepen','geslapen','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='slapen'  AND part_of_speech='verb' LIMIT 1)),
('aanbieden','bied','biedt','biedt','biedt','bieden','bood','boden','aangeboden','hebben','aan', true, true,  true,  false,(SELECT id FROM words WHERE word='aanbieden'  AND part_of_speech='verb' LIMIT 1)),
('aangeven','geef','geeft','geeft','geeft','geven','gaf','gaven','aangegeven','hebben','aan', true, true,  true,  false,(SELECT id FROM words WHERE word='aangeven'   AND part_of_speech='verb' LIMIT 1)),
('afspreken','spreek','spreekt','spreekt','spreekt','spreken','sprak','spraken','afgesproken','hebben','af', true, true,  true,  false,(SELECT id FROM words WHERE word='afspreken'  AND part_of_speech='verb' LIMIT 1)),
('inleveren','lever','levert','levert','levert','leveren','leverde','leverden','ingeleverd','hebben','in', true, false, false, false,(SELECT id FROM words WHERE word='inleveren'  AND part_of_speech='verb' LIMIT 1)),
('inschrijven','schrijf','schrijft','schrijft','schrijft','schrijven','schreef','schreven','ingeschreven','hebben','in', true, true,  true,  false,(SELECT id FROM words WHERE word='inschrijven' AND part_of_speech='verb' LIMIT 1)),
('nazeggen','zeg','zegt','zegt','zegt','zeggen','zei','zeiden','nagezegd','hebben','na', true, true,  false, false,(SELECT id FROM words WHERE word='nazeggen'   AND part_of_speech='verb' LIMIT 1)),
('opbouwen','bouw','bouwt','bouwt','bouwt','bouwen','bouwde','bouwden','opgebouwd','hebben','op', true, false, false, false,(SELECT id FROM words WHERE word='opbouwen'   AND part_of_speech='verb' LIMIT 1)),
('uitdiepen','diep','diept','diept','diept','diepen','diepte','diepten','uitgediept','hebben','uit', true, false, false, false,(SELECT id FROM words WHERE word='uitdiepen'  AND part_of_speech='verb' LIMIT 1)),
('uiten','uit','uit','uit','uit','uiten','uitte','uitten','geuit','hebben',NULL, false, false, false, false,(SELECT id FROM words WHERE word='uiten'      AND part_of_speech='verb' LIMIT 1)),
('uitvoeren','voer','voert','voert','voert','voeren','voerde','voerden','uitgevoerd','hebben','uit', true, false, false, false,(SELECT id FROM words WHERE word='uitvoeren'  AND part_of_speech='verb' LIMIT 1)),
('voorkomen','kom','komt','komt','komt','komen','kwam','kwamen','voorgekomen','zijn','voor', true, true,  true,  false,(SELECT id FROM words WHERE word='voorkomen'  AND part_of_speech='verb' LIMIT 1)),
('voorstellen','stel','stelt','stelt','stelt','stellen','stelde','stelden','voorgesteld','hebben','voor', true, false, false, false,(SELECT id FROM words WHERE word='voorstellen'AND part_of_speech='verb' LIMIT 1)),
('antwoorden','antwoord','antwoordt','antwoordt','antwoordt','antwoorden','antwoordde','antwoordden','geantwoord','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='antwoorden' AND part_of_speech='verb' LIMIT 1)),
('begeleiden','begeleid','begeleidt','begeleidt','begeleidt','begeleiden','begeleidde','begeleidden','begeleid','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='begeleiden' AND part_of_speech='verb' LIMIT 1)),
('behandelen','behandel','behandelt','behandelt','behandelt','behandelen','behandelde','behandelden','behandeld','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='behandelen' AND part_of_speech='verb' LIMIT 1)),
('bevatten','bevat','bevat','bevat','bevat','bevatten','bevatte','bevatten','bevat','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='bevatten'   AND part_of_speech='verb' LIMIT 1)),
('bellen','bel','belt','belt','belt','bellen','belde','belden','gebeld','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='bellen'     AND part_of_speech='verb' LIMIT 1)),
('duren','duur','duurt','duurt','duurt','duren','duurde','duurden','geduurd','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='duren'     AND part_of_speech='verb' LIMIT 1)),
('gebruiken','gebruik','gebruikt','gebruikt','gebruikt','gebruiken','gebruikte','gebruikten','gebruikt','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='gebruiken'  AND part_of_speech='verb' LIMIT 1)),
('illustreren','illustreer','illustreert','illustreert','illustreert','illustreren','illustreerde','illustreerden','geïllustreerd','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='illustreren'AND part_of_speech='verb' LIMIT 1)),
('kopen','koop','koopt','koopt','koopt','kopen','kocht','kochten','gekocht','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='kopen'     AND part_of_speech='verb' LIMIT 1)),
('kampen','kamp','kampt','kampt','kampt','kampen','kampte','kampten','gekampt','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='kampen'    AND part_of_speech='verb' LIMIT 1)),
('kijken','kijk','kijkt','kijkt','kijkt','kijken','keek','keken','gekeken','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='kijken'    AND part_of_speech='verb' LIMIT 1)),
('kiezen','kies','kiest','kiest','kiest','kiezen','koos','kozen','gekozen','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='kiezen'    AND part_of_speech='verb' LIMIT 1)),
('krijgen','krijg','krijgt','krijgt','krijgt','krijgen','kreeg','kregen','gekregen','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='krijgen'   AND part_of_speech='verb' LIMIT 1)),
('kruisen','kruis','kruist','kruist','kruist','kruisen','kruiste','kruisten','gekruist','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='kruisen'   AND part_of_speech='verb' LIMIT 1)),
('landen','land','landt','landt','landt','landen','landde','landden','geland','zijn',NULL,false,false,false,false,(SELECT id FROM words WHERE word='landen'    AND part_of_speech='verb' LIMIT 1)),
('leiden','leid','leidt','leidt','leidt','leiden','leidde','leidden','geleid','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='leiden'    AND part_of_speech='verb' LIMIT 1)),
('leren','leer','leert','leert','leert','leren','leerde','leerden','geleerd','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='leren'     AND part_of_speech='verb' LIMIT 1)),
('leveren','lever','levert','levert','levert','leveren','leverde','leverden','geleverd','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='leveren'   AND part_of_speech='verb' LIMIT 1)),
('lopen','loop','loopt','loopt','loopt','lopen','liep','liepen','gelopen','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='lopen'     AND part_of_speech='verb' LIMIT 1)),
('mennen','men','ment','ment','ment','mennen','mende','menden','gemend','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='mennen'     AND part_of_speech='verb' LIMIT 1)),
('oefenen','oefen','oefent','oefent','oefent','oefenen','oefende','oefenden','geoefend','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='oefenen'   AND part_of_speech='verb' LIMIT 1)),
('ontvangen','ontvang','ontvangt','ontvangt','ontvangt','ontvangen','ontving','ontvingen','ontvangen','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='ontvangen'  AND part_of_speech='verb' LIMIT 1)),
('ontwerpen','ontwerp','ontwerpt','ontwerpt','ontwerpt','ontwerpen','ontwierp','ontwierpen','ontworpen','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='ontwerpen'  AND part_of_speech='verb' LIMIT 1)),
('plaatsen','plaats','plaatst','plaatst','plaatst','plaatsen','plaatste','plaatsten','geplaatst','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='plaatsen'  AND part_of_speech='verb' LIMIT 1)),
('spreken','spreek','spreekt','spreekt','spreekt','spreken','sprak','spraken','gesproken','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='spreken'   AND part_of_speech='verb' LIMIT 1)),
('sluiten','sluit','sluit','sluit','sluit','sluiten','sloot','sloten','gesloten','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='sluiten'   AND part_of_speech='verb' LIMIT 1)),
('spelen','speel','speelt','speelt','speelt','spelen','speelde','speelden','gespeeld','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='spelen'    AND part_of_speech='verb' LIMIT 1)),
('staan','sta','staat','staat','staat','staan','stond','stonden','gestaan','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='staan'     AND part_of_speech='verb' LIMIT 1)),
('stellen','stel','stelt','stelt','stelt','stellen','stelde','stelden','gesteld','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='stellen'   AND part_of_speech='verb' LIMIT 1)),
('sturen','stuur','stuurt','stuurt','stuurt','sturen','stuurde','stuurden','gestuurd','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='sturen'    AND part_of_speech='verb' LIMIT 1)),
('studeren','studeer','studeert','studeert','studeert','studeren','studeerde','studeerden','gestudeerd','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='studeren'  AND part_of_speech='verb' LIMIT 1)),
('toetsen','toets','toetst','toetst','toetst','toetsen','toetste','toetsten','getoetst','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='toetsen'   AND part_of_speech='verb' LIMIT 1)),
('vinden','vind','vindt','vindt','vindt','vinden','vond','vonden','gevonden','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='vinden'    AND part_of_speech='verb' LIMIT 1)),
('voelen','voel','voelt','voelt','voelt','voelen','voelde','voelden','gevoeld','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='voelen'    AND part_of_speech='verb' LIMIT 1)),
('bestaan','bestaan','bestaat','bestaat','bestaat','bestaan','bestond','bestonden','bestaan','hebben',NULL,false,true, true, false,(SELECT id FROM words WHERE word='bestaan'   AND part_of_speech='verb' LIMIT 1)),
('blijven','blijf','blijft','blijft','blijft','blijven','bleef','bleven','gebleven','zijn',NULL,false,true, true, false,(SELECT id FROM words WHERE word='blijven'   AND part_of_speech='verb' LIMIT 1)),
('delen','deel','deelt','deelt','deelt','delen','deelde','deelden','gedeeld','hebben',NULL,false,false,false,false,(SELECT id FROM words WHERE word='delen' AND part_of_speech='verb' LIMIT 1))
ON CONFLICT (word_id) DO NOTHING;

-- Insert sample users for testing
INSERT INTO app_users (username, email, level_id) VALUES 
('demo_user', 'demo@example.com', (SELECT id FROM levels WHERE level = 'A2')),
('test_user', 'test@example.com', (SELECT id FROM levels WHERE level = 'A1'))
ON CONFLICT (username) DO NOTHING;

-- Note: Level target counts can be added later if needed
-- Currently using actual word counts from the database
