-- 01_seed.sql
-- Complete seed data for Dutch Language Learning API
-- Auto-generated from dutch_words.json and dutch-learning-backup.json
-- This file is automatically executed after schema creation

-- Insert CEFR levels
INSERT INTO levels (level) VALUES 
('A1'), ('A2'), ('B1'), ('B2'), ('C1'), ('C2')
ON CONFLICT (level) DO NOTHING;

-- Insert comprehensive categories
INSERT INTO categories (category) VALUES 
('fruits'), ('animals'), ('colors'), ('numbers'), ('family'), 
('food'), ('clothing'), ('transportation'), ('house'), ('body'),
('time'), ('weather'), ('emotions'), ('verbs'), ('prepositions'),
('common'), ('daily-life'), ('work'), ('school'), ('sports'),
('articles'), ('pronouns'), ('conjunctions'), ('adjectives'),
('adverbs'), ('other')
ON CONFLICT (category) DO NOTHING;

-- Insert all vocabulary words
DO $$
DECLARE
    a1_level_id INTEGER;
    a2_level_id INTEGER;
    b1_level_id INTEGER;
    b2_level_id INTEGER;
    c1_level_id INTEGER;
    c2_level_id INTEGER;
BEGIN
    -- Get level IDs
    SELECT id INTO a1_level_id FROM levels WHERE level = 'A1';
    SELECT id INTO a2_level_id FROM levels WHERE level = 'A2';
    SELECT id INTO b1_level_id FROM levels WHERE level = 'B1';
    SELECT id INTO b2_level_id FROM levels WHERE level = 'B2';
    SELECT id INTO c1_level_id FROM levels WHERE level = 'C1';
    SELECT id INTO c2_level_id FROM levels WHERE level = 'C2';


    -- A1 Level Words (45 words)
    INSERT INTO words (word, part_of_speech, meaning, level_id) VALUES
    ('aan', 'preposition', 'to, on, at', a1_level_id),
    ('acht', 'noun', 'eight, attention', a1_level_id),
    ('als', 'conjunction', 'as, if, when', a1_level_id),
    ('zijn', 'verb', 'are', a1_level_id),
    ('goed', 'adjective', 'best, dear', a1_level_id),
    ('bij', 'preposition', 'at, near, with, by', a1_level_id),
    ('de', 'article', 'the', a1_level_id),
    ('drie', 'numeral', 'three', a1_level_id),
    ('een', 'article', 'a, an, one', a1_level_id),
    ('en', 'conjunction', 'and', a1_level_id),
    ('gaan', 'verb', 'to go', a1_level_id),
    ('goed', 'verb', 'good, well', a1_level_id),
    ('hebben', 'verb', 'have', a1_level_id),
    ('hebben', 'verb', 'to have', a1_level_id),
    ('het', 'noun', 'the, it', a1_level_id),
    ('hij', 'noun', 'he', a1_level_id),
    ('ik', 'noun', 'I', a1_level_id),
    ('in', 'preposition', 'in, into', a1_level_id),
    ('jij', 'noun', 'you', a1_level_id),
    ('jullie', 'noun', 'you all, you guys', a1_level_id),
    ('komen', 'verb', 'to come', a1_level_id),
    ('met', 'preposition', 'with', a1_level_id),
    ('negen', 'numeral', 'nine', a1_level_id),
    ('of', 'conjunction', 'or, if', a1_level_id),
    ('om', 'preposition', 'around, at, to', a1_level_id),
    ('onder', 'preposition', 'under, below', a1_level_id),
    ('op', 'preposition', 'on, at, up', a1_level_id),
    ('oud', 'adjective', 'old', a1_level_id),
    ('over', 'preposition', 'over, about, above', a1_level_id),
    ('te', 'preposition', 'to, at', a1_level_id),
    ('ter', 'preposition', 'at, to', a1_level_id),
    ('tien', 'numeral', 'ten', a1_level_id),
    ('twaalf', 'numeral', 'twelve', a1_level_id),
    ('twee', 'numeral', 'two', a1_level_id),
    ('uit', 'preposition', 'out, from', a1_level_id),
    ('van', 'preposition', 'of, from', a1_level_id),
    ('via', 'preposition', 'via, through', a1_level_id),
    ('vier', 'numeral', 'four', a1_level_id),
    ('vijf', 'numeral', 'five', a1_level_id),
    ('voor', 'preposition', 'for, before, in front of', a1_level_id),
    ('wij', 'noun', 'we', a1_level_id),
    ('zes', 'numeral', 'six', a1_level_id),
    ('zeven', 'numeral', 'seven', a1_level_id),
    ('zij', 'noun', 'they, she', a1_level_id),
    ('zijn', 'verb', 'to be, his, its', a1_level_id)
    ON CONFLICT (word, meaning) DO NOTHING;

    -- A2 Level Words (368 words)
    INSERT INTO words (word, part_of_speech, meaning, level_id) VALUES
    ('aanbieden', 'verb', 'to offer, to provide', a2_level_id),
    ('aandacht', 'noun', 'attention, focus', a2_level_id),
    ('aangeven', 'verb', 'to indicate, to declare, to report', a2_level_id),
    ('achthonderdzesentwintig', 'numeral', 'eight hundred twenty-six', a2_level_id),
    ('adre', 'noun', 'address', a2_level_id),
    ('af', 'verb', 'off, finished, away', a2_level_id),
    ('afghanistan', 'noun', 'Afghanistan', a2_level_id),
    ('afspreken', 'verb', 'to arrange, to agree, to make an appointment', a2_level_id),
    ('al', 'verb', 'already, all, though', a2_level_id),
    ('alle', 'determiner', 'all, every', a2_level_id),
    ('allebei', 'noun', 'both', a2_level_id),
    ('alleen', 'verb', 'alone, only, just', a2_level_id),
    ('allemaal', 'noun', 'all, everybody, everything', a2_level_id),
    ('almere', 'noun', 'Almere', a2_level_id),
    ('amerika', 'noun', 'America', a2_level_id),
    ('andere', 'adjective', 'other, different', a2_level_id),
    ('antwoord', 'noun', 'to answer, answers', a2_level_id),
    ('aspect', 'noun', 'aspects', a2_level_id),
    ('audiocds', 'noun', 'audio CDs', a2_level_id),
    ('bagage', 'noun', 'baggage, luggage', a2_level_id),
    ('be', 'verb', 'to be, Belgium', a2_level_id),
    ('b', 'noun', 'a bit, a little', a2_level_id),
    ('behulp', 'noun', 'help, assistance', a2_level_id),
    ('besen', 'verb', 'best, quite', a2_level_id),
    ('bestaan', 'noun', 'to exist, existence', a2_level_id),
    ('bevatten', 'verb', 'to contain, to include', a2_level_id),
    ('bijbehorende', 'adjective', 'corresponding, accompanying, associated', a2_level_id),
    ('bijlag', 'noun', 'attachments, appendices', a2_level_id),
    ('blijven', 'verb', 'to stay, to remain', a2_level_id),
    ('boek', 'noun', 'book', a2_level_id),
    ('bruin', 'adjective', 'brown', a2_level_id),
    ('cd', 'noun', 'CD, compact disc', a2_level_id),
    ('centrum', 'noun', 'center, centre', a2_level_id),
    ('china', 'noun', 'China', a2_level_id),
    ('chinee', 'noun', 'Chinese', a2_level_id),
    ('contact', 'noun', 'contact', a2_level_id),
    ('contro', 'noun', 'control, check', a2_level_id),
    ('cursist', 'noun', 'student, course participant', a2_level_id),
    ('cursist', 'noun', 'students, course participants', a2_level_id),
    ('cursu', 'noun', 'course, class', a2_level_id),
    ('daarvan', 'verb', 'of that, from that', a2_level_id),
    ('dag', 'noun', 'day, hello, goodbye', a2_level_id),
    ('dan', 'verb', 'then, than', a2_level_id),
    ('dat', 'noun', 'that', a2_level_id),
    ('deel', 'noun', 'part, portion, share', a2_level_id),
    ('deen', 'noun', 'Dane', a2_level_id),
    ('deens', 'adjective', 'Danish', a2_level_id),
    ('del', 'noun', 'to share, to divide, parts', a2_level_id),
    ('denemark', 'noun', 'Denmark', a2_level_id),
    ('deze', 'noun', 'this, these', a2_level_id),
    ('dialog', 'noun', 'dialogues, conversations', a2_level_id),
    ('dialoog', 'noun', 'dialogue, conversation', a2_level_id),
    ('dit', 'noun', 'this', a2_level_id),
    ('do', 'verb', 'to do', a2_level_id),
    ('docent', 'noun', 'teacher, lecturer, instructor', a2_level_id),
    ('doen', 'verb', 'do', a2_level_id),
    ('doel', 'noun', 'goal, target, purpose', a2_level_id),
    ('doeld', 'verb', 'aims, targets', a2_level_id),
    ('doen', 'verb', 'to do, to make', a2_level_id),
    ('door', 'preposition', 'through, by, because of', a2_level_id),
    ('druk', 'noun', 'busy, pressure, print', a2_level_id),
    ('duits', 'adjective', 'German', a2_level_id),
    ('duren', 'verb', 'to last, to take time', a2_level_id),
    ('eenentwintig', 'numeral', 'twenty-one', a2_level_id),
    ('effec', 'noun', 'effect', a2_level_id),
    ('element', 'noun', 'elements', a2_level_id),
    ('elk', 'determiner', 'each, every', a2_level_id),
    ('email', 'noun', 'email, e-mail', a2_level_id),
    ('engels', 'adjective', 'English', a2_level_id),
    ('enof', 'conjunction', 'and/or', a2_level_id),
    ('er', 'noun', 'there, it', a2_level_id),
    ('eruien', 'verb', 'out of it, from it', a2_level_id),
    ('ervaring', 'noun', 'experiences', a2_level_id),
    ('europees', 'adjective', 'European', a2_level_id),
    ('even', 'verb', 'just, for a moment, equal', a2_level_id),
    ('eveneens', 'verb', 'also, likewise, as well', a2_level_id),
    ('exam', 'noun', 'exam, examination', a2_level_id),
    ('fas', 'noun', 'phases, stages', a2_level_id),
    ('foto', 'noun', 'photos, pictures', a2_level_id),
    ('frans', 'adjective', 'French', a2_level_id),
    ('frans', 'noun', 'French people, the French', a2_level_id),
    ('geboren', 'adjective', 'born', a2_level_id),
    ('gedacht', 'noun', 'thoughts', a2_level_id),
    ('geen', 'determiner', 'no, none, not any', a2_level_id),
    ('gehoord', 'verb', 'heard', a2_level_id),
    ('gelden', 'verb', 'to be valid, to apply, to count', a2_level_id),
    ('gele', 'adjective', 'yellow', a2_level_id),
    ('gelukkig', 'verb', 'happy, fortunately, lucky', a2_level_id),
    ('gen', 'noun', 'gene', a2_level_id),
    ('gesloten', 'adjective', 'closed, shut', a2_level_id),
    ('gesprek', 'noun', 'conversation, talk, discussion', a2_level_id),
    ('getall', 'noun', 'numbers', a2_level_id),
    ('geval', 'noun', 'case, situation', a2_level_id),
    ('geven', 'verb', 'to give', a2_level_id),
    ('goede', 'adjective', 'good', a2_level_id),
    ('graag', 'verb', 'gladly, willingly, like to', a2_level_id),
    ('hallo', 'interjection', 'hello, hi', a2_level_id),
    ('heten', 'verb', 'to be called, to be named', a2_level_id),
    ('hi', 'interjection', 'hi', a2_level_id),
    ('hier', 'verb', 'here', a2_level_id)
    ON CONFLICT (word, meaning) DO NOTHING;

    INSERT INTO words (word, part_of_speech, meaning, level_id) VALUES
    ('hiermee', 'verb', 'with this, hereby', a2_level_id),
    ('hijzij', 'noun', 'he/she, he or she', a2_level_id),
    ('hoe', 'verb', 'how', a2_level_id),
    ('hoeven', 'verb', 'to need to, to have to', a2_level_id),
    ('honderdachtenzeventig', 'numeral', 'one hundred seventy-eight', a2_level_id),
    ('hoofd', 'noun', 'head, main', a2_level_id),
    ('houden', 'verb', 'to keep, to hold, to maintain', a2_level_id),
    ('hui', 'noun', 'house, home', a2_level_id),
    ('huiswerk', 'noun', 'homework', a2_level_id),
    ('huren', 'verb', 'to rent, to hire', a2_level_id),
    ('ieder', 'determiner', 'each, every', a2_level_id),
    ('iedere', 'determiner', 'each, every', a2_level_id),
    ('iets', 'noun', 'something, anything', a2_level_id),
    ('ii', 'other', 'ii', a2_level_id),
    ('internet', 'noun', 'internet', a2_level_id),
    ('into', 'preposition', 'into', a2_level_id),
    ('intranet', 'noun', 'intranet', a2_level_id),
    ('isbn', 'noun', 'ISBN', a2_level_id),
    ('jaar', 'noun', 'year', a2_level_id),
    ('je', 'noun', 'you, your', a2_level_id),
    ('jkl', 'other', 'JKL', a2_level_id),
    ('jouw', 'determiner', 'your', a2_level_id),
    ('juisen', 'verb', 'correct, right, just', a2_level_id),
    ('jui', 'adjective', 'correct, right', a2_level_id),
    ('kamer', 'noun', 'room, chamber', a2_level_id),
    ('kamp', 'noun', 'camps, to camp', a2_level_id),
    ('kunnen', 'verb', 'can, able to', a2_level_id),
    ('kenni', 'noun', 'knowledge, acquaintance', a2_level_id),
    ('kiezen', 'verb', 'to choose, to select', a2_level_id),
    ('kijken', 'verb', 'to look, to watch', a2_level_id),
    ('komkomen', 'verb', 'comes', a2_level_id),
    ('koningin', 'noun', 'queen', a2_level_id),
    ('kopenhag', 'noun', 'Copenhagen', a2_level_id),
    ('krijgen', 'verb', 'to get, to receive', a2_level_id),
    ('kroon', 'noun', 'crown', a2_level_id),
    ('kruis', 'noun', 'to cross, crosses', a2_level_id),
    ('kunnen', 'verb', 'to be able to, can', a2_level_id),
    ('land', 'noun', 'land, country', a2_level_id),
    ('land', 'noun', 'countries, to land', a2_level_id),
    ('lange', 'adjective', 'long', a2_level_id),
    ('language', 'noun', 'languages', a2_level_id),
    ('layout', 'noun', 'layout', a2_level_id),
    ('leeftijd', 'noun', 'age', a2_level_id),
    ('leergang', 'noun', 'course, curriculum', a2_level_id),
    ('lees', 'verb', 'read', a2_level_id),
    ('leeuw', 'noun', 'lion', a2_level_id),
    ('leid', 'noun', 'to lead, Leiden', a2_level_id),
    ('leiden', 'verb', 'leads', a2_level_id),
    ('leren', 'verb', 'to learn, to teach', a2_level_id),
    ('lesstof', 'noun', 'course material, curriculum', a2_level_id),
    ('letters', 'noun', 'letters', a2_level_id),
    ('leuk', 'adjective', 'nice, fun, pleasant', a2_level_id),
    ('lever', 'noun', 'liver', a2_level_id),
    ('leveren', 'verb', 'to deliver, to supply', a2_level_id),
    ('lexicale', 'adjective', 'lexical', a2_level_id),
    ('lezen', 'verb', 'to read', a2_level_id),
    ('liedje', 'noun', 'songs', a2_level_id),
    ('los', 'adjective', 'loose, free, separate', a2_level_id),
    ('mogen', 'verb', 'may, allowed to', a2_level_id),
    ('mail', 'noun', 'mail, email', a2_level_id),
    ('maken', 'verb', 'to make, to create', a2_level_id),
    ('marokko', 'noun', 'Morocco', a2_level_id),
    ('meer', 'noun', 'more, lake', a2_level_id),
    ('meneer', 'noun', 'mister, sir', a2_level_id),
    ('mening', 'noun', 'opinions, views', a2_level_id),
    ('mennen', 'verb', 'to lead, to drive', a2_level_id),
    ('mens', 'noun', 'people, humans', a2_level_id),
    ('middel', 'noun', 'means, method, medium', a2_level_id),
    ('mijn', 'noun', 'my, mine', a2_level_id),
    ('model', 'noun', 'model', a2_level_id),
    ('moderne', 'adjective', 'modern', a2_level_id),
    ('moeten', 'verb', 'to have to, must', a2_level_id),
    ('mogen', 'verb', 'to be allowed to, may', a2_level_id),
    ('naam', 'noun', 'name', a2_level_id),
    ('naar', 'preposition', 'to, towards, at', a2_level_id),
    ('nam', 'noun', 'names', a2_level_id),
    ('nazeggen', 'verb', 'to repeat, to say after', a2_level_id),
    ('nee', 'interjection', 'no', a2_level_id),
    ('negentienzevenenzestig', 'numeral', 'nineteen sixty-seven', a2_level_id),
    ('neen', 'verb', 'just, net, clean', a2_level_id),
    ('netwerk', 'noun', 'network', a2_level_id),
    ('nieen', 'verb', 'not', a2_level_id),
    ('niets', 'noun', 'nothing', a2_level_id),
    ('nijmeg', 'noun', 'Nijmegen', a2_level_id),
    ('niveau', 'noun', 'level, standard', a2_level_id),
    ('noch', 'conjunction', 'neither, nor', a2_level_id),
    ('noemer', 'noun', 'denominator', a2_level_id),
    ('nt', 'other', 'nt', a2_level_id),
    ('nu', 'verb', 'now', a2_level_id),
    ('oefe', 'noun', 'exercise', a2_level_id),
    ('oefenen', 'verb', 'to practice, to exercise', a2_level_id),
    ('oefening', 'noun', 'exercise, practice', a2_level_id),
    ('oefening', 'noun', 'exercises, practices', a2_level_id),
    ('omslag', 'noun', 'cover, envelope', a2_level_id),
    ('ontact', 'noun', 'contact', a2_level_id),
    ('ook', 'verb', 'also, too, as well', a2_level_id),
    ('opbouwen', 'verb', 'to build up, to construct', a2_level_id),
    ('opdracht', 'noun', 'assignment, task, order', a2_level_id),
    ('opdracht', 'noun', 'assignments, tasks', a2_level_id),
    ('open', 'adjective', 'open', a2_level_id)
    ON CONFLICT (word, meaning) DO NOTHING;

    INSERT INTO words (word, part_of_speech, meaning, level_id) VALUES
    ('openbaar', 'adjective', 'public, open', a2_level_id),
    ('oplossing', 'noun', 'solution', a2_level_id),
    ('oplossing', 'noun', 'solutions', a2_level_id),
    ('persoon', 'noun', 'person', a2_level_id),
    ('pizzeria', 'noun', 'pizzeria', a2_level_id),
    ('plaats', 'noun', 'places, to place', a2_level_id),
    ('pol', 'noun', 'Poland', a2_level_id),
    ('prins', 'noun', 'prince', a2_level_id),
    ('pronom', 'noun', 'pronoun', a2_level_id),
    ('puzzel', 'noun', 'puzzle', a2_level_id),
    ('recht', 'noun', 'rights, law', a2_level_id),
    ('redactie', 'noun', 'editorial staff, editing', a2_level_id),
    ('reeks', 'noun', 'series, row', a2_level_id),
    ('relatief', 'adjective', 'relative', a2_level_id),
    ('rol', 'noun', 'role, roll', a2_level_id),
    ('rome', 'noun', 'Rome', a2_level_id),
    ('roo', 'noun', 'rose', a2_level_id),
    ('rusland', 'noun', 'Russia', a2_level_id),
    ('russ', 'noun', 'Russians', a2_level_id),
    ('russisch', 'adjective', 'Russian', a2_level_id),
    ('schema', 'noun', 'scheme, diagram', a2_level_id),
    ('setting', 'noun', 'setting', a2_level_id),
    ('situa', 'noun', 'situation', a2_level_id),
    ('sluiten', 'verb', 'to close, to shut', a2_level_id),
    ('sommige', 'determiner', 'some, certain', a2_level_id),
    ('spaans', 'adjective', 'Spanish', a2_level_id),
    ('span', 'noun', 'Spain', a2_level_id),
    ('spraak', 'noun', 'speech, language', a2_level_id),
    ('spreeken', 'verb', 'speaks', a2_level_id),
    ('spreken', 'verb', 'to speak, to talk', a2_level_id),
    ('staan', 'verb', 'to stand, to be located', a2_level_id),
    ('staats', 'noun', 'state', a2_level_id),
    ('stad', 'noun', 'city, town', a2_level_id),
    ('stat', 'noun', 'states, United States', a2_level_id),
    ('stellen', 'verb', 'to put, to place, to set', a2_level_id),
    ('straat', 'noun', 'street', a2_level_id),
    ('strep', 'noun', 'stripes, lines', a2_level_id),
    ('studeren', 'verb', 'to study', a2_level_id),
    ('studie', 'noun', 'study, research', a2_level_id),
    ('stukk', 'noun', 'pieces, parts', a2_level_id),
    ('sturen', 'verb', 'to send, to steer', a2_level_id),
    ('subthema', 'noun', 'subtheme', a2_level_id),
    ('symbool', 'noun', 'symbol', a2_level_id),
    ('taal', 'noun', 'language, tongue', a2_level_id),
    ('tal', 'noun', 'languages', a2_level_id),
    ('tekst', 'noun', 'text', a2_level_id),
    ('tekst', 'noun', 'texts', a2_level_id),
    ('thema', 'noun', 'theme, topic', a2_level_id),
    ('thema', 'noun', 'themes, topics', a2_level_id),
    ('tief', 'adjective', 'deep', a2_level_id),
    ('tie', 'noun', 'ties', a2_level_id),
    ('toets', 'noun', 'to test, tests', a2_level_id),
    ('turki', 'noun', 'Turkey', a2_level_id),
    ('twaalfhonderddrienzeventig', 'numeral', 'one thousand two hundred seventy-three', a2_level_id),
    ('tweehonderdeenennegentig', 'numeral', 'two hundred ninety-one', a2_level_id),
    ('tweehonderdzevenenveertig', 'numeral', 'two hundred forty-seven', a2_level_id),
    ('tweemaal', 'verb', 'twice, two times', a2_level_id),
    ('typisch', 'adjective', 'typical', a2_level_id),
    ('uitdiepen', 'verb', 'to elaborate, to deepen', a2_level_id),
    ('uiten', 'verb', 'to express, to voice', a2_level_id),
    ('uitgave', 'noun', 'edition, publication', a2_level_id),
    ('uitgever', 'noun', 'publisher', a2_level_id),
    ('uitspraak', 'noun', 'pronunciation, speech', a2_level_id),
    ('uitspraakoefening', 'noun', 'pronunciation exercises', a2_level_id),
    ('uitvoeren', 'verb', 'to execute, to perform', a2_level_id),
    ('utrecht', 'noun', 'Utrecht', a2_level_id),
    ('uw', 'determiner', 'your', a2_level_id),
    ('uzelf', 'noun', 'yourself', a2_level_id),
    ('vak', 'noun', 'subject, field, profession', a2_level_id),
    ('vakantie', 'noun', 'vacation, holiday', a2_level_id),
    ('vanaf', 'preposition', 'from, starting from', a2_level_id),
    ('vandaag', 'verb', 'today', a2_level_id),
    ('vandaan', 'verb', 'from, away from', a2_level_id),
    ('va', 'adjective', 'fixed, certain, sure', a2_level_id),
    ('verbum', 'noun', 'verb', a2_level_id),
    ('vierentachtig', 'numeral', 'eighty-four', a2_level_id),
    ('vierentwintig', 'numeral', 'twenty-four', a2_level_id),
    ('vijfennegentig', 'numeral', 'ninety-five', a2_level_id),
    ('vinden', 'verb', 'to find, to think', a2_level_id),
    ('voel', 'verb', 'feel', a2_level_id),
    ('volgende', 'adjective', 'next, following', a2_level_id),
    ('volgens', 'preposition', 'according to', a2_level_id),
    ('volgorde', 'noun', 'order, sequence', a2_level_id),
    ('voorafgaande', 'adjective', 'preceding, previous', a2_level_id),
    ('voorbeeld', 'noun', 'example', a2_level_id),
    ('voorbeeldoplossin', 'noun', 'example solution', a2_level_id),
    ('voorbehouden', 'adjective', 'reserved, withheld', a2_level_id),
    ('voorkomen', 'verb', 'to prevent, to appear', a2_level_id),
    ('voornaam', 'noun', 'first name, given name', a2_level_id),
    ('voornamelijk', 'verb', 'mainly, primarily', a2_level_id),
    ('voorstellen', 'verb', 'to introduce, to suggest', a2_level_id),
    ('voorwoord', 'noun', 'foreword, preface', a2_level_id),
    ('vorm', 'noun', 'form, shape', a2_level_id),
    ('vrag', 'noun', 'questions, to ask', a2_level_id),
    ('vriend', 'noun', 'friends', a2_level_id),
    ('vriendin', 'noun', 'girlfriend, female friend', a2_level_id),
    ('vries', 'verb', 'freeze', a2_level_id),
    ('vullen', 'verb', 'to fill', a2_level_id),
    ('waar', 'verb', 'where, true', a2_level_id),
    ('waarin', 'verb', 'in which, wherein', a2_level_id)
    ON CONFLICT (word, meaning) DO NOTHING;

    INSERT INTO words (word, part_of_speech, meaning, level_id) VALUES
    ('wanneer', 'verb', 'when', a2_level_id),
    ('wa', 'noun', 'was, laundry', a2_level_id),
    ('wat', 'noun', 'what, which', a2_level_id),
    ('wb', 'other', 'wb', a2_level_id),
    ('we', 'noun', 'we', a2_level_id),
    ('website', 'noun', 'website', a2_level_id),
    ('week', 'noun', 'week', a2_level_id),
    ('weten', 'verb', 'know', a2_level_id),
    ('weg', 'noun', 'road, way, away', a2_level_id),
    ('welk', 'determiner', 'which', a2_level_id),
    ('welke', 'determiner', 'which', a2_level_id),
    ('wereld', 'noun', 'world', a2_level_id),
    ('werkboek', 'noun', 'workbook', a2_level_id),
    ('werken', 'verb', 'to work', a2_level_id),
    ('wie', 'noun', 'who', a2_level_id),
    ('willen', 'verb', 'want', a2_level_id),
    ('wonen', 'verb', 'to live, to reside', a2_level_id),
    ('woonen', 'verb', 'lives, resides', a2_level_id),
    ('woord', 'noun', 'word', a2_level_id),
    ('woord', 'noun', 'words', a2_level_id),
    ('worden', 'verb', 'to become, to be', a2_level_id),
    ('ze', 'noun', 'they, them, she', a2_level_id),
    ('zeggen', 'verb', 'say', a2_level_id),
    ('zeggen', 'verb', 'to say, to tell', a2_level_id),
    ('zelf', 'noun', 'self, myself, yourself', a2_level_id),
    ('zeshonderd', 'numeral', 'six hundred', a2_level_id),
    ('zetten', 'verb', 'to put, to place, to set', a2_level_id),
    ('zevenhonderdnegenennegentig', 'numeral', 'seven hundred ninety-nine', a2_level_id),
    ('zien', 'verb', 'see', a2_level_id),
    ('zin', 'noun', 'sentence, sense, desire', a2_level_id),
    ('zinn', 'noun', 'sentences', a2_level_id),
    ('zo', 'verb', 'so, thus, like this', a2_level_id),
    ('zoal', 'verb', 'such as, for example', a2_level_id),
    ('zoeken', 'verb', 'to search, to look for', a2_level_id),
    ('zonder', 'preposition', 'without', a2_level_id),
    ('zowel', 'verb', 'both, as well as', a2_level_id),
    ('zullen', 'verb', 'will, shall', a2_level_id),
    ('zwed', 'noun', 'Sweden', a2_level_id),
    ('appel', 'noun', 'apple', a2_level_id),
    ('banaan', 'noun', 'banana', a2_level_id),
    ('peer', 'noun', 'pear', a2_level_id),
    ('druif', 'noun', 'grape', a2_level_id),
    ('kers', 'noun', 'cherry', a2_level_id),
    ('meloen', 'noun', 'melon', a2_level_id),
    ('perzik', 'noun', 'peach', a2_level_id),
    ('pruim', 'noun', 'plum', a2_level_id),
    ('aardbei', 'noun', 'strawberry', a2_level_id),
    ('citroen', 'noun', 'lemon', a2_level_id),
    ('bank', 'noun', 'bank', a2_level_id),
    ('bank', 'noun', 'bench', a2_level_id),
    ('arm', 'noun', 'arm', a2_level_id),
    ('arm', 'adjective', 'poor', a2_level_id),
    ('kunnen', 'verb', 'can', a2_level_id),
    ('kunn', 'noun', 'jug', a2_level_id),
    ('lopen', 'verb', 'to walk', a2_level_id),
    ('lopen', 'verb', 'to run', a2_level_id),
    ('zien', 'verb', 'to see', a2_level_id),
    ('zien', 'verb', 'to understand', a2_level_id),
    ('land', 'noun', 'country', a2_level_id),
    ('land', 'noun', 'land', a2_level_id),
    ('roken', 'verb', 'to smoke', a2_level_id),
    ('roken', 'verb', 'to emit smoke', a2_level_id),
    ('spelen', 'verb', 'to play', a2_level_id),
    ('spelen', 'verb', 'to perform', a2_level_id),
    ('bellen', 'verb', 'to call', a2_level_id),
    ('bellen', 'verb', 'to ring', a2_level_id),
    ('kopen', 'verb', 'to buy', a2_level_id),
    ('kopen', 'verb', 'to purchase', a2_level_id)
    ON CONFLICT (word, meaning) DO NOTHING;

    -- B1 Level Words (108 words)
    INSERT INTO words (word, part_of_speech, meaning, level_id) VALUES
    ('achternaam', 'noun', 'last name, surname', b1_level_id),
    ('akoestische', 'adjective', 'acoustic', b1_level_id),
    ('anderstalige', 'adjective', 'non-Dutch speaking, foreign language', b1_level_id),
    ('anderstalig', 'noun', 'non-Dutch speakers', b1_level_id),
    ('barcelona', 'noun', 'Barcelona', b1_level_id),
    ('begeleiden', 'verb', 'to guide, to accompany, to supervise', b1_level_id),
    ('begrip', 'noun', 'understanding, concept, comprehension', b1_level_id),
    ('behandelen', 'verb', 'to treat, to handle, to deal with', b1_level_id),
    ('belangrijk', 'adjective', 'most important, main', b1_level_id),
    ('benodigde', 'adjective', 'required, needed', b1_level_id),
    ('boodschapp', 'noun', 'groceries, shopping, messages', b1_level_id),
    ('bronvermelding', 'noun', 'source citation, bibliography', b1_level_id),
    ('buitenland', 'noun', 'abroad, foreign countries', b1_level_id),
    ('centenhandleiding', 'noun', 'cent guide, manual', b1_level_id),
    ('communicatie', 'noun', 'communication', b1_level_id),
    ('communicatieve', 'adjective', 'communicative', b1_level_id),
    ('doorlopen', 'verb', 'to walk through, to continue', b1_level_id),
    ('doorwerken', 'verb', 'to work through, to continue working', b1_level_id),
    ('driedelige', 'adjective', 'three-part, tripartite', b1_level_id),
    ('drieduizend', 'numeral', 'three thousand', b1_level_id),
    ('duitsland', 'noun', 'Germany', b1_level_id),
    ('emailadre', 'noun', 'email address', b1_level_id),
    ('erasmusbeurs', 'noun', 'Erasmus grant, Erasmus scholarship', b1_level_id),
    ('filmische', 'adjective', 'filmic, cinematic', b1_level_id),
    ('frankrijk', 'noun', 'France', b1_level_id),
    ('functionele', 'adjective', 'functional', b1_level_id),
    ('geboortedatum', 'noun', 'date of birth', b1_level_id),
    ('geboortejaar', 'noun', 'year of birth', b1_level_id),
    ('gebruiken', 'verb', 'to use, to utilize', b1_level_id),
    ('gedurende', 'preposition', 'during, for the duration of', b1_level_id),
    ('geografie', 'noun', 'geography', b1_level_id),
    ('gevoelens', 'noun', 'feelings, emotions', b1_level_id),
    ('grafische', 'adjective', 'graphic, graphical', b1_level_id),
    ('grammaticale', 'adjective', 'grammatical', b1_level_id),
    ('grammaticaoefening', 'noun', 'grammar exercises', b1_level_id),
    ('hieronder', 'verb', 'below, underneath', b1_level_id),
    ('hoofdstuk', 'noun', 'chapter', b1_level_id),
    ('hoofdstukk', 'noun', 'chapters', b1_level_id),
    ('hoofdthema', 'noun', 'main theme, central theme', b1_level_id),
    ('hoogopgeleide', 'adjective', 'highly educated, well-educated', b1_level_id),
    ('huisnummer', 'noun', 'house number', b1_level_id),
    ('illustreren', 'verb', 'to illustrate', b1_level_id),
    ('infinitief', 'noun', 'infinitive', b1_level_id),
    ('informatie', 'noun', 'information', b1_level_id),
    ('ingescand', 'adjective', 'scanned in', b1_level_id),
    ('inhoudsopgave', 'noun', 'table of contents', b1_level_id),
    ('inleveren', 'verb', 'to hand in, to submit', b1_level_id),
    ('inschrijven', 'verb', 'to register, to enroll', b1_level_id),
    ('instrument', 'noun', 'instrument, tool', b1_level_id),
    ('interrogatief', 'adjective', 'interrogative', b1_level_id),
    ('introductiepagina', 'noun', 'introduction page, homepage', b1_level_id),
    ('italiaans', 'adjective', 'Italian', b1_level_id),
    ('italiaanse', 'adjective', 'Italian', b1_level_id),
    ('kruiswoordpuzzel', 'noun', 'crossword puzzle', b1_level_id),
    ('landeneiland', 'noun', 'countries and islands', b1_level_id),
    ('leestekst', 'noun', 'reading text', b1_level_id),
    ('leestekst', 'noun', 'reading texts', b1_level_id),
    ('luisteren', 'verb', 'to listen', b1_level_id),
    ('luistermateriaal', 'noun', 'listening material', b1_level_id),
    ('luisteroefening', 'noun', 'listening exercise', b1_level_id),
    ('luisteroefening', 'noun', 'listening exercises', b1_level_id),
    ('medewerking', 'noun', 'cooperation, collaboration', b1_level_id),
    ('moedertaal', 'noun', 'mother tongue, native language', b1_level_id),
    ('mogelijk', 'adjective', 'possible, feasible', b1_level_id),
    ('nationaliteit', 'noun', 'nationality', b1_level_id),
    ('nederland', 'noun', 'Netherlands', b1_level_id),
    ('nederlands', 'adjective', 'Dutch', b1_level_id),
    ('nederlandse', 'adjective', 'Dutch', b1_level_id),
    ('nederlandstalige', 'adjective', 'Dutch-speaking', b1_level_id),
    ('onderdeel', 'noun', 'component, part', b1_level_id),
    ('onderscheiden', 'verb', 'to distinguish, to differentiate', b1_level_id),
    ('onderstrepen', 'verb', 'to underline, to emphasize', b1_level_id),
    ('onderwerp', 'noun', 'subjects, topics', b1_level_id),
    ('onderwijsinstelling', 'noun', 'educational institutions', b1_level_id),
    ('ontvangen', 'verb', 'to receive, to welcome', b1_level_id),
    ('ontwerpen', 'verb', 'to design, to create', b1_level_id),
    ('pgomezgmailcom', 'noun', 'email address', b1_level_id),
    ('productief', 'adjective', 'productive', b1_level_id),
    ('programma', 'noun', 'program, schedule', b1_level_id),
    ('projectcordinatie', 'noun', 'project coordination', b1_level_id),
    ('realistische', 'adjective', 'realistic', b1_level_id),
    ('receptief', 'adjective', 'receptive', b1_level_id),
    ('referentiekader', 'noun', 'reference framework', b1_level_id),
    ('samenleving', 'noun', 'society', b1_level_id),
    ('schriftelijke', 'adjective', 'written', b1_level_id),
    ('schrijfoefening', 'noun', 'writing exercises', b1_level_id),
    ('schrijven', 'verb', 'to write', b1_level_id),
    ('secretaresse', 'noun', 'secretary', b1_level_id),
    ('taalelement', 'noun', 'language elements', b1_level_id),
    ('tekstboek', 'noun', 'textbook', b1_level_id),
    ('telefoonnummer', 'noun', 'telephone number', b1_level_id),
    ('theorie', 'noun', 'theory', b1_level_id),
    ('toestemming', 'noun', 'permission, consent', b1_level_id),
    ('transcriptie', 'noun', 'transcriptions', b1_level_id),
    ('universiteit', 'noun', 'university', b1_level_id),
    ('vaardighed', 'noun', 'skills, abilities', b1_level_id),
    ('vaardigheid', 'noun', 'skill, ability', b1_level_id),
    ('verenigde', 'adjective', 'united', b1_level_id),
    ('vermenigvuldigen', 'verb', 'to multiply', b1_level_id),
    ('verticaal', 'adjective', 'vertical', b1_level_id)
    ON CONFLICT (word, meaning) DO NOTHING;

    INSERT INTO words (word, part_of_speech, meaning, level_id) VALUES
    ('verwerken', 'verb', 'to process, to work with', b1_level_id),
    ('vierfasemodel', 'noun', 'four-phase model', b1_level_id),
    ('volwassen', 'noun', 'adults', b1_level_id),
    ('vormgeving', 'noun', 'design, layout', b1_level_id),
    ('vriendvriendin', 'noun', 'boyfriend/girlfriend', b1_level_id),
    ('woordenlijst', 'noun', 'word list, vocabulary', b1_level_id),
    ('woordenschat', 'noun', 'vocabulary', b1_level_id),
    ('woordzoeker', 'noun', 'word search', b1_level_id)
    ON CONFLICT (word, meaning) DO NOTHING;

    -- Auto-categorize words by part of speech
    INSERT INTO category_words (category_id, word_id)
    SELECT c.id, w.id 
    FROM categories c, words w 
    WHERE c.category = 'verbs' AND w.part_of_speech = 'verb'
    ON CONFLICT (category_id, word_id) DO NOTHING;

    INSERT INTO category_words (category_id, word_id)
    SELECT c.id, w.id 
    FROM categories c, words w 
    WHERE c.category = 'adjectives' AND w.part_of_speech = 'adjective'
    ON CONFLICT (category_id, word_id) DO NOTHING;

    INSERT INTO category_words (category_id, word_id)
    SELECT c.id, w.id 
    FROM categories c, words w 
    WHERE c.category = 'numbers' AND w.part_of_speech = 'numeral'
    ON CONFLICT (category_id, word_id) DO NOTHING;

    INSERT INTO category_words (category_id, word_id)
    SELECT c.id, w.id 
    FROM categories c, words w 
    WHERE c.category = 'prepositions' AND w.part_of_speech = 'preposition'
    ON CONFLICT (category_id, word_id) DO NOTHING;

    INSERT INTO category_words (category_id, word_id)
    SELECT c.id, w.id 
    FROM categories c, words w 
    WHERE c.category = 'articles' AND w.part_of_speech = 'article'
    ON CONFLICT (category_id, word_id) DO NOTHING;

    INSERT INTO category_words (category_id, word_id)
    SELECT c.id, w.id 
    FROM categories c, words w 
    WHERE c.category = 'pronouns' AND w.part_of_speech = 'pronoun'
    ON CONFLICT (category_id, word_id) DO NOTHING;

END $$;

-- Insert sample users for testing
INSERT INTO app_users (username, email, level_id) VALUES 
('demo_user', 'demo@example.com', (SELECT id FROM levels WHERE level = 'A2')),
('test_user', 'test@example.com', (SELECT id FROM levels WHERE level = 'A1'))
ON CONFLICT (username) DO NOTHING;
